/* ════════ EXERCICES STATIQUES SUPPLÉMENTAIRES ════════
   Pool de secours pour les royaumes non-maths : permet un lancement
   instantané même quand le Worker IA est indisponible. Le Worker
   continue à enrichir le pool en arrière-plan via maybeAutoGenerate
   quand unseen < 5.
   20 exercices par niveau, format identique à exercises.js.
*/
EX.push(
/* ═══ PHYSIQUE CE2 — Matière / Lumière ═══ */
{id:"phy2_01",lv:"physique-ce2",cat:"États de la matière",diff:1,q:"Lequel de ces objets est un solide ?",ch:["L'eau du robinet","Une pierre","De la fumée","Du jus d'orange"],ans:1,se:"Une pierre garde toujours la même forme : c'est un solide.",pourquoi:"L'eau et le jus sont liquides (ils coulent). La fumée est un gaz (elle se disperse dans l'air).",regle:"Solide = forme fixe ; Liquide = prend la forme du récipient ; Gaz = remplit tout l'espace.",sk:"États de la matière"},
{id:"phy2_02",lv:"physique-ce2",cat:"États de la matière",diff:1,q:"Quand on chauffe de l'eau jusqu'à 100°C, elle se transforme en…",ch:["Glace","Vapeur","Sucre","Pierre"],ans:1,se:"À 100°C l'eau bout et se transforme en vapeur d'eau (un gaz). C'est l'évaporation.",pourquoi:"La glace se forme quand l'eau refroidit (à 0°C), pas quand elle chauffe.",regle:"Chauffer un liquide → il s'évapore en gaz. Refroidir un gaz → il se condense en liquide.",sk:"Changements d'état"},
{id:"phy2_03",lv:"physique-ce2",cat:"Lumière",diff:1,q:"Lequel de ces objets est une SOURCE de lumière ?",ch:["Un miroir","La Lune","Le Soleil","Un livre"],ans:2,se:"Le Soleil produit lui-même de la lumière : c'est une source primaire.",pourquoi:"La Lune et un miroir RENVOIENT la lumière du Soleil mais n'en produisent pas eux-mêmes.",regle:"Source primaire = produit sa propre lumière (Soleil, lampe, bougie). Source secondaire = renvoie la lumière (Lune, miroir).",sk:"Sources de lumière"},
{id:"phy2_04",lv:"physique-ce2",cat:"Lumière",diff:2,q:"Pourquoi vois-tu ton ombre quand tu marches au soleil ?",ch:["Ton corps brille","Ton corps bloque la lumière","Le sol est noir","La lumière a peur de toi"],ans:1,se:"Ton corps est OPAQUE : il empêche la lumière de passer, et il y a une zone sombre derrière toi.",pourquoi:"Ton corps n'émet pas de lumière (sinon il brillerait dans le noir).",regle:"L'ombre se forme derrière un objet opaque éclairé : la lumière ne peut pas le traverser.",sk:"Ombres et opacité"},
{id:"phy2_05",lv:"physique-ce2",cat:"États de la matière",diff:2,q:"L'air autour de toi est…",ch:["Un solide","Un liquide","Un gaz","Rien du tout"],ans:2,se:"L'air est un mélange de gaz (azote, oxygène…). C'est invisible mais c'est bien de la matière : ça pèse.",pourquoi:"Si tu ne vois pas quelque chose, ça ne veut pas dire qu'il n'y a rien : l'air a un poids.",regle:"Un gaz n'a ni forme propre ni volume propre. Il occupe tout l'espace disponible.",sk:"Reconnaître les gaz"},
{id:"phy2_06",lv:"physique-ce2",cat:"Lumière",diff:1,q:"Quel objet laisse passer toute la lumière ?",ch:["Un mur en brique","Une vitre propre","Une feuille de carton","Un pull en laine"],ans:1,se:"La vitre est TRANSPARENTE : la lumière la traverse complètement, donc on voit à travers.",pourquoi:"Mur, carton et pull sont OPAQUES : la lumière ne passe pas, on ne voit pas à travers.",regle:"Transparent (vitre, eau pure) → on voit à travers. Translucide (papier calque) → la lumière passe mais flou. Opaque (mur) → rien ne passe.",sk:"Matériaux et lumière"},
{id:"phy2_07",lv:"physique-ce2",cat:"États de la matière",diff:2,q:"Que se passe-t-il quand on met un glaçon dans un verre à température ambiante ?",ch:["Il grossit","Il fond et devient liquide","Il devient gaz","Il reste pareil pour toujours"],ans:1,se:"À température ambiante (>0°C), la glace fond et redevient de l'eau liquide : c'est la fusion.",pourquoi:"Il faudrait des températures très hautes (100°C) pour qu'il devienne gaz directement.",regle:"Solide → Liquide = fusion. Liquide → Solide = solidification.",sk:"Fusion et solidification"},
{id:"phy2_08",lv:"physique-ce2",cat:"Lumière",diff:2,q:"Pour qu'on puisse voir un objet, il faut…",ch:["Que la lumière entre dans nos yeux depuis l'objet","Que l'objet émette une voix","Que le ciel soit bleu","Que l'objet soit chaud"],ans:0,se:"On voit un objet quand de la lumière (émise ou renvoyée par l'objet) entre dans nos yeux.",pourquoi:"Dans l'obscurité totale (aucune lumière), on ne voit rien — même les yeux ouverts.",regle:"Voir = des rayons de lumière atteignent nos yeux depuis l'objet observé.",sk:"Conditions de la vision"},
{id:"phy2_09",lv:"physique-ce2",cat:"États de la matière",diff:2,q:"Quel exemple montre une condensation ?",ch:["L'eau qui bout dans une casserole","La buée sur une vitre froide","Un glaçon qui fond","Le sel qui se dissout"],ans:1,se:"La vapeur d'eau de l'air se transforme en gouttelettes liquides au contact de la vitre froide : c'est la condensation.",pourquoi:"L'eau qui bout est une évaporation (liquide → gaz), pas le contraire.",regle:"Condensation = un gaz se transforme en liquide quand il refroidit.",sk:"Changements d'état"},
{id:"phy2_10",lv:"physique-ce2",cat:"Lumière",diff:3,q:"Si tu te tiens loin d'une lampe, ton ombre est plutôt…",ch:["Plus petite","Plus grande","Identique","Invisible"],ans:0,se:"Plus tu es loin de la source, plus les rayons arrivent presque parallèles → ton ombre est plus petite et plus nette.",pourquoi:"Près de la lampe, les rayons divergent fortement → ton ombre s'agrandit.",regle:"Plus la source est loin, plus l'ombre se rapproche de la taille réelle de l'objet.",sk:"Géométrie de l'ombre"},
{id:"phy2_11",lv:"physique-ce2",cat:"États de la matière",diff:1,q:"Le miel, c'est plutôt…",ch:["Un solide","Un liquide épais","Un gaz","Une poudre"],ans:1,se:"Le miel coule lentement et prend la forme du pot : c'est un liquide (visqueux).",pourquoi:"Sa lenteur peut faire croire à un solide, mais il s'écoule, donc liquide.",regle:"Tout ce qui s'écoule (même très lentement) et prend la forme du récipient = liquide.",sk:"Reconnaître les liquides"},
{id:"phy2_12",lv:"physique-ce2",cat:"Lumière",diff:2,q:"Pourquoi fait-il nuit ?",ch:["Le Soleil s'éteint","La Terre tourne et notre côté n'est plus face au Soleil","La Lune cache le Soleil","Les nuages couvrent le ciel"],ans:1,se:"La Terre tourne sur elle-même en 24h. Quand notre côté n'est plus face au Soleil, c'est la nuit.",pourquoi:"Le Soleil ne s'éteint jamais — il continue à éclairer l'autre côté de la Terre (où c'est le jour).",regle:"Jour/nuit = rotation de la Terre sur elle-même en 24 heures.",sk:"Alternance jour/nuit"},
{id:"phy2_13",lv:"physique-ce2",cat:"États de la matière",diff:2,q:"Si tu mets de l'eau au congélateur, elle devient…",ch:["De la vapeur","De la glace","Du sel","Plus rien"],ans:1,se:"Le congélateur est très froid (-18°C). L'eau gèle à 0°C et devient de la glace : c'est la solidification.",pourquoi:"La vapeur, c'est l'inverse : il faut chauffer fort.",regle:"En dessous de 0°C, l'eau devient de la glace (solide).",sk:"Solidification"},
{id:"phy2_14",lv:"physique-ce2",cat:"Lumière",diff:1,q:"Lequel n'est PAS une source de lumière ?",ch:["Une bougie allumée","Une étoile","Un feu de cheminée","Un livre fermé"],ans:3,se:"Un livre ne produit pas de lumière. Il faut une lampe pour le lire dans le noir.",pourquoi:"Bougie, étoile et feu produisent tous leur propre lumière.",regle:"Source de lumière = produit elle-même de la lumière.",sk:"Sources de lumière"},
{id:"phy2_15",lv:"physique-ce2",cat:"États de la matière",diff:3,q:"Sur le couvercle d'une casserole d'eau qui bout, tu vois des gouttes. D'où viennent-elles ?",ch:["De l'eau qui a sauté","De la vapeur qui se recondense au contact du couvercle plus froid","Du couvercle qui fond","De la magie"],ans:1,se:"La vapeur monte, touche le couvercle (plus froid) et se transforme en gouttelettes : c'est la condensation.",pourquoi:"L'eau ne saute pas si haut ; le couvercle métallique ne fond pas à 100°C.",regle:"Quand un gaz rencontre une surface froide, il se condense en liquide.",sk:"Cycle de l'eau"},
{id:"phy2_16",lv:"physique-ce2",cat:"Lumière",diff:2,q:"Quel matériau est translucide ?",ch:["Un mur","Du papier calque","Une vitre","Du métal"],ans:1,se:"Le papier calque laisse passer un peu de lumière mais on ne voit pas net à travers : c'est translucide.",pourquoi:"La vitre est transparente (on voit net), le mur et le métal sont opaques (rien ne passe).",regle:"Translucide = la lumière passe mais l'image est floue.",sk:"Transparence"},
{id:"phy2_17",lv:"physique-ce2",cat:"États de la matière",diff:2,q:"Si tu laisses une flaque d'eau au soleil, que se passe-t-il ?",ch:["Elle grossit","Elle disparaît peu à peu (évaporation)","Elle devient noire","Rien"],ans:1,se:"La chaleur du soleil fait passer l'eau de l'état liquide à l'état gazeux : la flaque s'évapore.",pourquoi:"La flaque ne grossit pas seule ; elle ne change pas de couleur.",regle:"Évaporation = un liquide se transforme en gaz au contact de l'air et de la chaleur.",sk:"Évaporation"},
{id:"phy2_18",lv:"physique-ce2",cat:"Lumière",diff:3,q:"L'ombre d'un arbre au sol pointe vers l'est. Le Soleil est donc…",ch:["À l'est","À l'ouest","Au nord","Au sud"],ans:1,se:"L'ombre se forme du côté OPPOSÉ à la source de lumière. Si l'ombre va vers l'est, le Soleil est à l'ouest.",pourquoi:"L'ombre n'est jamais du même côté que la lumière : elle est derrière l'objet.",regle:"L'ombre pointe toujours dans la direction OPPOSÉE à la source de lumière.",sk:"Direction de l'ombre"},
{id:"phy2_19",lv:"physique-ce2",cat:"États de la matière",diff:1,q:"Le brouillard est constitué de…",ch:["Petites gouttes d'eau en suspension dans l'air","De la fumée","Du sable","Du gaz pur"],ans:0,se:"Le brouillard est formé de minuscules gouttelettes d'eau qui flottent dans l'air. C'est presque comme un nuage au sol.",pourquoi:"La fumée vient d'un feu ; ici il n'y a pas de feu.",regle:"Brouillard = vapeur d'eau condensée en gouttelettes dans l'air froid près du sol.",sk:"Eau dans l'air"},
{id:"phy2_20",lv:"physique-ce2",cat:"Lumière",diff:2,q:"Tu allumes une lampe dans une pièce vide. La lumière voyage…",ch:["En zigzag","En ligne droite","En spirale","Pas du tout"],ans:1,se:"La lumière se propage en LIGNE DROITE dans tous les sens à partir de la source.",pourquoi:"Si elle voyageait en zigzag, ton ombre n'aurait pas de forme nette.",regle:"Dans un milieu transparent (air, eau), la lumière voyage en ligne droite.",sk:"Propagation de la lumière"}
);

EX.push(
/* ═══ PHYSIQUE CM1 — Énergie / Électricité ═══ */
{id:"phyc1_01",lv:"physique-cm1",cat:"Énergie",diff:1,q:"Lequel n'est PAS une source d'énergie ?",ch:["Le Soleil","Le vent","Le pétrole","Une brique"],ans:3,se:"Une brique stocke de la chaleur mais ne produit pas d'énergie utilisable. Soleil, vent et pétrole sont des sources.",pourquoi:"Confusion possible : la brique peut emmagasiner la chaleur du soleil mais elle n'en produit pas.",regle:"Source d'énergie = produit de l'énergie utilisable (Soleil, vent, eau, charbon, pétrole, gaz, uranium, biomasse).",sk:"Sources d'énergie"},
{id:"phyc1_02",lv:"physique-cm1",cat:"Énergie",diff:1,q:"L'énergie solaire est…",ch:["Polluante","Renouvelable","Limitée","Dangereuse"],ans:1,se:"Le Soleil brille depuis 4,5 milliards d'années et continuera longtemps : c'est une énergie renouvelable et propre.",pourquoi:"Elle ne produit pas de gaz polluants pendant son utilisation.",regle:"Énergies renouvelables : Soleil, vent, eau, biomasse, géothermie. Non renouvelables : pétrole, gaz, charbon, uranium.",sk:"Énergies renouvelables"},
{id:"phyc1_03",lv:"physique-cm1",cat:"Électricité",diff:1,q:"Pour qu'une ampoule s'allume dans un circuit, il faut…",ch:["Une seule pile","Un fil cassé","Un circuit fermé avec une pile","De l'eau"],ans:2,se:"Le courant doit pouvoir circuler en BOUCLE complète : pile → fil → ampoule → fil → pile.",pourquoi:"Si le circuit est ouvert (fil cassé), le courant ne passe pas et l'ampoule reste éteinte.",regle:"Circuit fermé = boucle complète. Circuit ouvert = boucle interrompue.",sk:"Circuit électrique"},
{id:"phyc1_04",lv:"physique-cm1",cat:"Électricité",diff:2,q:"Lequel est un bon CONDUCTEUR d'électricité ?",ch:["Le bois","Le plastique","Le cuivre","Le verre"],ans:2,se:"Les métaux (cuivre, fer, or…) laissent passer le courant : ce sont des conducteurs.",pourquoi:"Bois, plastique, verre sont des isolants : ils empêchent le passage du courant.",regle:"Conducteur = laisse passer le courant (métaux, eau salée). Isolant = bloque le courant (plastique, bois sec, verre).",sk:"Conducteurs et isolants"},
{id:"phyc1_05",lv:"physique-cm1",cat:"Électricité",diff:2,q:"Pourquoi les fils électriques sont entourés de plastique ?",ch:["Pour faire joli","Pour que le courant ne s'échappe pas et qu'on ne s'électrocute pas","Pour les rendre plus solides","Pour qu'ils brillent"],ans:1,se:"Le plastique est un ISOLANT. Il empêche le courant de sortir du fil et protège des électrocutions.",pourquoi:"Sans isolant, toucher le fil te ferait passer du courant dans le corps.",regle:"Les isolants protègent des dangers de l'électricité.",sk:"Sécurité électrique"},
{id:"phyc1_06",lv:"physique-cm1",cat:"Énergie",diff:2,q:"D'où vient l'énergie d'une éolienne ?",ch:["Du vent","Du Soleil","De la lune","Du pétrole"],ans:0,se:"Le vent fait tourner les pales, qui font tourner un générateur produisant de l'électricité.",pourquoi:"L'énergie de départ est mécanique (mouvement de l'air), elle devient électrique.",regle:"Éolienne = transforme l'énergie du vent en énergie électrique.",sk:"Conversions d'énergie"},
{id:"phyc1_07",lv:"physique-cm1",cat:"Électricité",diff:1,q:"Une pile fournit du courant grâce à…",ch:["L'air à l'intérieur","Une réaction chimique","Sa couleur","Sa forme"],ans:1,se:"Une pile contient des produits chimiques qui réagissent et libèrent de l'énergie électrique.",pourquoi:"La forme et la couleur n'ont aucun rôle dans le fonctionnement.",regle:"Pile = stockage d'énergie chimique transformée en électricité.",sk:"Fonctionnement de la pile"},
{id:"phyc1_08",lv:"physique-cm1",cat:"Énergie",diff:2,q:"Quelle action consomme le PLUS d'énergie ?",ch:["Allumer une LED 1 heure","Faire tourner un four 1 heure","Charger un téléphone","Lire un livre"],ans:1,se:"Le four chauffe à 200°C : il consomme énormément d'énergie. Les LED et la charge sont très économes.",pourquoi:"Lire un livre ne consomme aucune énergie électrique.",regle:"Plus un appareil chauffe (four, radiateur, sèche-cheveux), plus il consomme.",sk:"Consommation énergétique"},
{id:"phyc1_09",lv:"physique-cm1",cat:"Électricité",diff:3,q:"Si on met deux ampoules en SÉRIE dans un circuit avec une pile, elles brillent…",ch:["Plus fort","Moins fort","Pareil","Pas du tout"],ans:1,se:"En série, le courant doit traverser les 2 ampoules à la suite : il est plus faible, donc chaque ampoule brille moins fort.",pourquoi:"On pourrait croire que 2 ampoules = 2 fois plus de lumière, mais c'est l'inverse en série.",regle:"En SÉRIE : ampoules moins lumineuses. En PARALLÈLE : ampoules à pleine puissance.",sk:"Série vs parallèle"},
{id:"phyc1_10",lv:"physique-cm1",cat:"Énergie",diff:1,q:"Pour économiser l'énergie à la maison, je dois…",ch:["Laisser la lumière allumée tout le temps","Éteindre les appareils que je n'utilise pas","Ouvrir le frigo souvent","Mettre la TV en veille toute la nuit"],ans:1,se:"Éteindre les appareils inutiles est le geste le plus efficace pour économiser l'énergie (et l'argent !).",pourquoi:"La veille consomme aussi de l'électricité (un peu mais en continu).",regle:"Éteindre > laisser en veille > laisser allumé.",sk:"Économies d'énergie"},
{id:"phyc1_11",lv:"physique-cm1",cat:"Électricité",diff:2,q:"Un interrupteur sert à…",ch:["Augmenter la puissance","Ouvrir ou fermer le circuit","Faire briller plus","Refroidir"],ans:1,se:"L'interrupteur ouvre le circuit (lumière éteinte) ou le ferme (lumière allumée).",pourquoi:"Il ne change pas la puissance, juste le passage du courant.",regle:"Interrupteur ouvert = pas de courant. Interrupteur fermé = courant passe.",sk:"Rôle de l'interrupteur"},
{id:"phyc1_12",lv:"physique-cm1",cat:"Énergie",diff:2,q:"Le pétrole, le gaz et le charbon sont des énergies…",ch:["Renouvelables","Fossiles, non renouvelables","Solaires","Magiques"],ans:1,se:"Ce sont des énergies fossiles : formées il y a des millions d'années à partir de matière organique. On les épuise.",pourquoi:"Une fois consommées, elles ne se reconstituent pas avant des millions d'années.",regle:"Énergies fossiles = pétrole, gaz, charbon. Limitées et polluantes (CO₂).",sk:"Énergies fossiles"},
{id:"phyc1_13",lv:"physique-cm1",cat:"Électricité",diff:3,q:"Dans un circuit en parallèle avec 2 ampoules, si une ampoule grille…",ch:["L'autre s'éteint aussi","L'autre continue à briller","Le circuit explose","La pile fond"],ans:1,se:"En parallèle, chaque ampoule a son propre chemin. Si l'une est cassée, l'autre fonctionne toujours.",pourquoi:"En série, les deux s'éteindraient. En parallèle, elles sont indépendantes.",regle:"En parallèle, les composants sont indépendants. C'est le branchement utilisé à la maison.",sk:"Circuits en parallèle"},
{id:"phyc1_14",lv:"physique-cm1",cat:"Énergie",diff:1,q:"L'énergie d'un panneau solaire vient de…",ch:["La lumière du Soleil","La pluie","Le vent","La nuit"],ans:0,se:"Les panneaux solaires transforment la lumière du Soleil directement en électricité.",pourquoi:"Sans soleil (la nuit), un panneau solaire ne produit pas d'électricité.",regle:"Panneau solaire = lumière → électricité (énergie photovoltaïque).",sk:"Énergie solaire"},
{id:"phyc1_15",lv:"physique-cm1",cat:"Électricité",diff:2,q:"L'eau salée est…",ch:["Un isolant","Un conducteur","Inerte","Magnétique"],ans:1,se:"L'eau salée laisse passer le courant : c'est pourquoi il est très dangereux d'utiliser de l'électricité près de l'eau.",pourquoi:"L'eau pure conduit peu, mais avec du sel (ou du calcaire), elle devient conductrice.",regle:"Ne JAMAIS utiliser d'appareil électrique avec les mains mouillées ou près d'une baignoire.",sk:"Sécurité électrique"},
{id:"phyc1_16",lv:"physique-cm1",cat:"Énergie",diff:3,q:"Un barrage hydroélectrique utilise l'énergie de…",ch:["L'eau qui tombe","Le vent","Le Soleil","Le feu"],ans:0,se:"L'eau du barrage tombe et fait tourner des turbines, qui produisent de l'électricité.",pourquoi:"C'est l'énergie du mouvement de l'eau (énergie mécanique) qui est convertie.",regle:"Hydroélectricité = énergie de l'eau en mouvement → électricité. Renouvelable.",sk:"Hydroélectricité"},
{id:"phyc1_17",lv:"physique-cm1",cat:"Électricité",diff:2,q:"Le symbole d'une pile dans un schéma est :",ch:["Un cercle","Deux barres parallèles, une longue et une courte","Une croix","Une étoile"],ans:1,se:"La barre longue représente le pôle + (positif), la barre courte le pôle – (négatif).",pourquoi:"Les schémas électriques utilisent des symboles standards pour chaque composant.",regle:"Pile : ⎮ (longue) = +, ⎮ (courte) = –.",sk:"Symboles électriques"},
{id:"phyc1_18",lv:"physique-cm1",cat:"Énergie",diff:2,q:"L'énergie nucléaire est produite à partir de…",ch:["L'eau","L'uranium","Le bois","Le sucre"],ans:1,se:"Les centrales nucléaires utilisent l'uranium : sa fission libère énormément d'énergie pour produire de l'électricité.",pourquoi:"L'uranium est un métal rare et radioactif (donc dangereux).",regle:"Nucléaire = uranium → chaleur → vapeur → turbine → électricité. Pas de CO₂ mais déchets radioactifs.",sk:"Énergie nucléaire"},
{id:"phyc1_19",lv:"physique-cm1",cat:"Électricité",diff:3,q:"Si tu doubles le nombre de piles dans un circuit en série, l'ampoule…",ch:["Reste pareil","Brille plus fort","Brille moins fort","S'éteint"],ans:1,se:"Plus de piles en série = plus de tension = plus de courant = ampoule plus brillante (attention, elle peut griller !).",pourquoi:"Les tensions s'additionnent en série : 2 piles de 1,5 V = 3 V au total.",regle:"En série, les tensions s'ajoutent. En parallèle, elles restent identiques.",sk:"Tension et brillance"},
{id:"phyc1_20",lv:"physique-cm1",cat:"Énergie",diff:1,q:"Un radiateur électrique transforme l'électricité en…",ch:["Lumière","Chaleur","Son","Vent"],ans:1,se:"Le radiateur transforme l'énergie électrique en chaleur (énergie thermique) pour réchauffer la pièce.",pourquoi:"Une lampe transforme l'électricité en lumière, un haut-parleur en son. Chaque appareil a sa fonction.",regle:"Conversion d'énergie : électrique → thermique (radiateur), lumineuse (lampe), mécanique (moteur), sonore (HP).",sk:"Conversions d'énergie"}
);

EX.push(
/* ═══ PHYSIQUE CM2 — Forces / Circuits ═══ */
{id:"phyc2_01",lv:"physique-cm2",cat:"Forces",diff:1,q:"Qu'est-ce qui fait tomber les objets vers le sol ?",ch:["Le vent","La gravité","La chaleur","La lumière"],ans:1,se:"La gravité est la force d'attraction de la Terre sur tous les objets. Elle les attire vers le centre de la Terre.",pourquoi:"Sans gravité, les objets flotteraient comme dans l'espace.",regle:"La gravité (ou pesanteur) attire tous les objets vers le bas.",sk:"Gravité"},
{id:"phyc2_02",lv:"physique-cm2",cat:"Forces",diff:1,q:"Quelle force ralentit un vélo qui descend une côte sans pédaler ?",ch:["La gravité","Les frottements (air + roue/sol)","La couleur du vélo","Aucune"],ans:1,se:"Les frottements de l'air et du contact pneu/sol ralentissent le vélo. Sans eux, il accélérerait sans cesse.",pourquoi:"La gravité l'accélère au contraire.",regle:"Les frottements s'opposent au mouvement.",sk:"Frottements"},
{id:"phyc2_03",lv:"physique-cm2",cat:"Circuits",diff:2,q:"Dans un circuit en SÉRIE avec 2 ampoules, si on enlève une ampoule…",ch:["L'autre brille plus","L'autre s'éteint","L'autre clignote","Le circuit explose"],ans:1,se:"Le circuit est ouvert, le courant ne peut plus passer, les deux ampoules sont éteintes.",pourquoi:"En parallèle, l'autre continuerait à briller.",regle:"En série, tout dépend de chaque composant : si un fait défaut, tout s'arrête.",sk:"Série"},
{id:"phyc2_04",lv:"physique-cm2",cat:"Forces",diff:2,q:"Une balle posée sur une table ne tombe pas car…",ch:["Elle est légère","La table exerce une force vers le haut","Elle est attirée par le plafond","Elle a peur"],ans:1,se:"La table pousse la balle vers le haut avec une force égale à la gravité : les forces s'équilibrent.",pourquoi:"Si la table était molle, la balle s'enfoncerait.",regle:"Quand un objet est immobile, les forces qui s'exercent sur lui s'équilibrent.",sk:"Équilibre des forces"},
{id:"phyc2_05",lv:"physique-cm2",cat:"Circuits",diff:2,q:"Le symbole d'une ampoule dans un schéma est :",ch:["Un cercle avec une croix dedans","Un carré","Un triangle","Une flèche"],ans:0,se:"L'ampoule se représente par un cercle avec un X (filament) à l'intérieur.",pourquoi:"Chaque composant a son symbole normalisé.",regle:"Lire un schéma = reconnaître les symboles standards.",sk:"Symboles électriques"},
{id:"phyc2_06",lv:"physique-cm2",cat:"Forces",diff:2,q:"Quelle unité mesure une force ?",ch:["Le mètre","Le newton (N)","Le litre","Le degré"],ans:1,se:"Une force se mesure en newton (N), en hommage au scientifique Isaac Newton.",pourquoi:"Le mètre mesure une distance, le litre un volume, le degré une température.",regle:"Force = newton (N). Sur Terre, 1 kg pèse environ 10 N.",sk:"Unité de force"},
{id:"phyc2_07",lv:"physique-cm2",cat:"Circuits",diff:3,q:"Pour mesurer la tension aux bornes d'une pile, j'utilise…",ch:["Un voltmètre","Un thermomètre","Une règle","Une boussole"],ans:0,se:"Le voltmètre mesure la tension électrique en volts (V). Une pile plate fait 4,5 V, une pile bouton souvent 1,5 V.",pourquoi:"L'ampèremètre mesure le courant (intensité), pas la tension.",regle:"Tension → voltmètre (en volts). Intensité → ampèremètre (en ampères).",sk:"Mesures électriques"},
{id:"phyc2_08",lv:"physique-cm2",cat:"Forces",diff:1,q:"L'aimant attire…",ch:["Tous les métaux","Le fer (et nickel, cobalt)","Le plastique","Le bois"],ans:1,se:"Les aimants attirent surtout le fer, le nickel et le cobalt. L'or, l'aluminium, le cuivre ne sont PAS attirés.",pourquoi:"Toucher un objet métallique avec un aimant ne suffit pas : il faut qu'il contienne du fer.",regle:"Aimant = attire les matériaux ferromagnétiques (fer, nickel, cobalt).",sk:"Magnétisme"},
{id:"phyc2_09",lv:"physique-cm2",cat:"Circuits",diff:2,q:"Pourquoi installe-t-on un disjoncteur dans une maison ?",ch:["Pour éclairer","Pour couper le courant en cas de problème","Pour faire du bruit","Pour décorer"],ans:1,se:"Le disjoncteur coupe automatiquement le courant en cas de surcharge ou de court-circuit, évitant les incendies.",pourquoi:"Sans disjoncteur, un court-circuit pourrait faire fondre les fils ou déclencher un feu.",regle:"Disjoncteur = sécurité. Il agit comme un interrupteur automatique.",sk:"Sécurité électrique"},
{id:"phyc2_10",lv:"physique-cm2",cat:"Forces",diff:3,q:"Sur la Lune, ton poids serait…",ch:["Identique à la Terre","6 fois plus léger","2 fois plus lourd","Nul"],ans:1,se:"La Lune attire 6 fois moins fort que la Terre. Tu pèserais 6 fois moins, mais ta MASSE resterait la même.",pourquoi:"La masse (quantité de matière) ne change pas. Le poids (force d'attraction) dépend de la planète.",regle:"Poids = masse × gravité. La gravité change selon la planète.",sk:"Poids vs masse"},
{id:"phyc2_11",lv:"physique-cm2",cat:"Circuits",diff:2,q:"Un court-circuit, c'est…",ch:["Un circuit trop petit","Quand les deux bornes de la pile se touchent directement","Un fil cassé","Une ampoule grillée"],ans:1,se:"Quand les bornes + et – se touchent (par un fil par exemple), un courant énorme passe et peut tout endommager.",pourquoi:"C'est dangereux : la pile peut chauffer, fuir, voire prendre feu.",regle:"Ne JAMAIS relier directement les deux bornes d'une pile.",sk:"Court-circuit"},
{id:"phyc2_12",lv:"physique-cm2",cat:"Forces",diff:2,q:"Pourquoi un parachute ralentit-il une chute ?",ch:["Il fait moins de bruit","Il augmente les frottements de l'air","Il devient plus lourd","Il vole"],ans:1,se:"La grande surface du parachute crée beaucoup de frottements avec l'air, ce qui freine la chute.",pourquoi:"Sans parachute, la résistance de l'air sur le corps seul est trop faible pour ralentir suffisamment.",regle:"Plus la surface en mouvement est grande, plus les frottements de l'air sont importants.",sk:"Résistance de l'air"},
{id:"phyc2_13",lv:"physique-cm2",cat:"Circuits",diff:3,q:"Pourquoi à la maison les ampoules sont-elles branchées en PARALLÈLE et pas en série ?",ch:["C'est plus joli","Pour qu'elles brillent à pleine puissance et soient indépendantes","Pour économiser","C'est plus court"],ans:1,se:"En parallèle, chaque ampoule reçoit la pleine tension du secteur (230 V) et fonctionne même si une autre grille.",pourquoi:"En série, elles seraient moins lumineuses et toutes liées : si une grille, tout s'éteint.",regle:"Maison = circuit en parallèle. Permet l'indépendance et la pleine puissance.",sk:"Circuits domestiques"},
{id:"phyc2_14",lv:"physique-cm2",cat:"Forces",diff:1,q:"Quand tu pousses un meuble, tu exerces sur lui…",ch:["Une force","Une chaleur","Un son","Une lumière"],ans:0,se:"Une poussée est une force. Elle peut faire bouger un objet, le déformer, ou changer sa direction.",pourquoi:"La chaleur, le son, la lumière ne sont pas des forces.",regle:"Force = action qui peut mettre en mouvement, déformer ou arrêter un objet.",sk:"Reconnaître une force"},
{id:"phyc2_15",lv:"physique-cm2",cat:"Circuits",diff:2,q:"Si une ampoule indique 4,5 V et qu'on la branche sur une pile de 9 V, elle…",ch:["Brille faiblement","Brille normalement","Grille car la tension est trop forte","Reste éteinte"],ans:2,se:"L'ampoule est faite pour 4,5 V. Avec 9 V, le filament chauffe trop et fond : l'ampoule grille.",pourquoi:"Toujours respecter la tension nominale d'un composant.",regle:"Tension d'usage > tension nominale = composant détruit.",sk:"Tension nominale"},
{id:"phyc2_16",lv:"physique-cm2",cat:"Forces",diff:3,q:"L'eau dans un verre exerce sur le fond une force appelée…",ch:["Pression","Vitesse","Lumière","Couleur"],ans:0,se:"Le poids de l'eau crée une pression sur le fond du verre. Plus il y a d'eau, plus la pression est forte.",pourquoi:"La pression dépend de la hauteur du liquide, pas de la forme du récipient.",regle:"Pression d'un liquide = poids de la colonne au-dessus / surface.",sk:"Pression"},
{id:"phyc2_17",lv:"physique-cm2",cat:"Circuits",diff:2,q:"L'unité de l'intensité électrique est :",ch:["Le volt","L'ampère","Le watt","L'ohm"],ans:1,se:"L'intensité (le débit du courant) se mesure en ampère (A), du nom du physicien français Ampère.",pourquoi:"Le volt mesure la tension, le watt la puissance, l'ohm la résistance.",regle:"Tension = volt (V), Intensité = ampère (A), Puissance = watt (W).",sk:"Unités électriques"},
{id:"phyc2_18",lv:"physique-cm2",cat:"Forces",diff:2,q:"Deux aimants se repoussent quand…",ch:["On rapproche un nord d'un sud","On rapproche deux nords (ou deux suds)","Ils sont chauds","Ils sont gros"],ans:1,se:"Pôles identiques (N–N ou S–S) se repoussent. Pôles opposés (N–S) s'attirent.",pourquoi:"Comme les aimants ne s'attirent pas tout le temps, beaucoup confondent.",regle:"Aimants : opposés s'attirent, semblables se repoussent.",sk:"Pôles magnétiques"},
{id:"phyc2_19",lv:"physique-cm2",cat:"Circuits",diff:3,q:"Une lampe LED consomme 5 W et une ampoule classique 60 W pour autant de lumière. Laquelle est plus économique ?",ch:["L'ampoule classique","La LED","C'est pareil","Aucune n'est économique"],ans:1,se:"À éclairage égal, la LED consomme 12 fois moins que l'ampoule classique → bien plus économique.",pourquoi:"L'ampoule classique transforme 90% de l'énergie en chaleur (perdue), la LED presque tout en lumière.",regle:"Plus la puissance est faible pour un même service, plus c'est économique.",sk:"Puissance et économie"},
{id:"phyc2_20",lv:"physique-cm2",cat:"Forces",diff:2,q:"Pour mesurer une force, j'utilise…",ch:["Un dynamomètre","Une balance","Un thermomètre","Une règle"],ans:0,se:"Le dynamomètre est un appareil avec un ressort qui s'allonge proportionnellement à la force exercée.",pourquoi:"La balance mesure la masse (en kg), pas la force.",regle:"Dynamomètre = mesure une force (en newton).",sk:"Mesure d'une force"}
);

EX.push(
/* ═══ HÉBREU — Alphabet (אבג) ═══ */
{id:"hebal_01",lv:"hebreu-alphabet",cat:"Alphabet",diff:1,q:"Quel est le nom de la première lettre de l'alphabet hébreu ?",ch:["Alef","Bet","Gimel","Dalet"],ans:0,se:"La première lettre de l'alphabet hébreu est א (Alef).",pourquoi:"Bet est la 2e lettre, Gimel la 3e, Dalet la 4e.",regle:"L'alphabet hébreu commence par : Alef (א), Bet (ב), Gimel (ג), Dalet (ד).",sk:"Ordre alphabétique"},
{id:"hebal_02",lv:"hebreu-alphabet",cat:"Alphabet",diff:1,q:"Quelle lettre s'écrit ב ?",ch:["Alef","Bet","Vet","Mem"],ans:1,se:"ב est la lettre Bet (la 2e de l'alphabet). Elle se prononce 'B' (ou 'V' sans dagesh).",pourquoi:"Alef est א, Mem est מ.",regle:"Bet (ב) = 2e lettre, son 'B' (ou 'V' selon contexte).",sk:"Reconnaissance des lettres"},
{id:"hebal_03",lv:"hebreu-alphabet",cat:"Alphabet",diff:1,q:"Combien de lettres compte l'alphabet hébreu ?",ch:["20","22","26","30"],ans:1,se:"L'alphabet hébreu compte 22 lettres (5 d'entre elles ont une forme finale particulière).",pourquoi:"L'alphabet français en a 26, mais l'hébreu n'en a que 22.",regle:"22 lettres dans l'alphabet hébreu, dont 5 ont une forme finale (sofit).",sk:"Structure de l'alphabet"},
{id:"hebal_04",lv:"hebreu-alphabet",cat:"Alphabet",diff:2,q:"Quelle lettre s'écrit ש ?",ch:["Sin/Shin","Mem","Nun","Pe"],ans:0,se:"ש est la lettre Shin (avec un point en haut à droite) ou Sin (point en haut à gauche).",pourquoi:"Mem est מ, Nun est נ.",regle:"Shin = 'Ch' comme dans Shabbat. Sin = 'S'.",sk:"Reconnaissance des lettres"},
{id:"hebal_05",lv:"hebreu-alphabet",cat:"Alphabet",diff:2,q:"Dans quel sens lit-on l'hébreu ?",ch:["De gauche à droite","De droite à gauche","De haut en bas","De bas en haut"],ans:1,se:"L'hébreu se lit et s'écrit de DROITE à GAUCHE, contrairement au français.",pourquoi:"Comme l'arabe, c'est une langue qui se lit de droite à gauche.",regle:"Hébreu = lecture de droite à gauche. Première lettre d'un mot = celle de droite.",sk:"Sens de lecture"},
{id:"hebal_06",lv:"hebreu-alphabet",cat:"Alphabet",diff:2,q:"Laquelle de ces lettres se prononce 'M' ?",ch:["נ","מ","ל","כ"],ans:1,se:"מ est la lettre Mem, qui correspond au son 'M'.",pourquoi:"נ = Nun (N), ל = Lamed (L), כ = Kaf (K).",regle:"Mem (מ) = son 'M'.",sk:"Sons des lettres"},
{id:"hebal_07",lv:"hebreu-alphabet",cat:"Alphabet",diff:2,q:"Quelle est la dernière lettre de l'alphabet hébreu ?",ch:["Alef","Tav","Resh","Shin"],ans:1,se:"La dernière lettre est ת (Tav). Elle correspond au son 'T'.",pourquoi:"Alef est la première (א).",regle:"Alphabet hébreu : commence par Alef (א), finit par Tav (ת).",sk:"Ordre alphabétique"},
{id:"hebal_08",lv:"hebreu-alphabet",cat:"Alphabet",diff:1,q:"Quelle lettre s'écrit א ?",ch:["Alef","Ayin","Het","Tav"],ans:0,se:"א est la lettre Alef, première de l'alphabet. Elle est silencieuse seule.",pourquoi:"Ayin est ע, Het est ח, Tav est ת.",regle:"Alef (א) = première lettre. Elle ne se prononce pas seule mais porte la voyelle.",sk:"Reconnaissance des lettres"},
{id:"hebal_09",lv:"hebreu-alphabet",cat:"Alphabet",diff:3,q:"Combien de lettres ont une forme FINALE (sofit) ?",ch:["3","5","7","10"],ans:1,se:"5 lettres : ך (Kaf), ם (Mem), ן (Nun), ף (Pe), ץ (Tsadi). On les utilise quand la lettre est en fin de mot.",pourquoi:"Les autres lettres gardent la même forme partout dans le mot.",regle:"5 lettres finales (sofit) : Kaf, Mem, Nun, Pe, Tsadi → ך ם ן ף ץ.",sk:"Lettres finales"},
{id:"hebal_10",lv:"hebreu-alphabet",cat:"Alphabet",diff:2,q:"Quelle lettre est-ce : ל ?",ch:["Lamed","Mem","Nun","Yod"],ans:0,se:"ל est la lettre Lamed, qui correspond au son 'L'.",pourquoi:"Mem est מ, Nun est נ, Yod est י.",regle:"Lamed (ל) = son 'L'.",sk:"Reconnaissance des lettres"},
{id:"hebal_11",lv:"hebreu-alphabet",cat:"Alphabet",diff:2,q:"Quel son fait la lettre ה (Hé) ?",ch:["'H' aspiré (souffle léger)","'P'","'T'","'K'"],ans:0,se:"ה (Hé) se prononce comme un H aspiré, un souffle léger (comme dans 'house' en anglais).",pourquoi:"En français il n'existe pas vraiment, mais c'est très proche du H anglais.",regle:"Hé (ה) = souffle léger 'H'.",sk:"Sons des lettres"},
{id:"hebal_12",lv:"hebreu-alphabet",cat:"Alphabet",diff:1,q:"Quelle est la 3e lettre de l'alphabet hébreu ?",ch:["Alef","Bet","Gimel","Dalet"],ans:2,se:"L'ordre est : 1) Alef, 2) Bet, 3) Gimel, 4) Dalet, 5) Hé…",pourquoi:"Bet est la 2e, Dalet la 4e.",regle:"Début de l'alphabet : Alef, Bet, Gimel, Dalet, Hé.",sk:"Ordre alphabétique"},
{id:"hebal_13",lv:"hebreu-alphabet",cat:"Alphabet",diff:3,q:"Quelle est la forme finale de la lettre Mem (מ) ?",ch:["ך","ם","ן","ץ"],ans:1,se:"En fin de mot, מ devient ם (Mem sofit).",pourquoi:"ך = Kaf finale, ן = Nun finale, ץ = Tsadi finale.",regle:"Mem : מ au milieu, ם à la fin.",sk:"Lettres finales"},
{id:"hebal_14",lv:"hebreu-alphabet",cat:"Alphabet",diff:2,q:"Laquelle est la lettre Yod ?",ch:["י","כ","ל","מ"],ans:0,se:"י (Yod) est la plus petite lettre de l'alphabet hébreu. Elle correspond au son 'I' ou 'Y'.",pourquoi:"כ = Kaf, ל = Lamed, מ = Mem.",regle:"Yod (י) = son 'I' ou 'Y'.",sk:"Reconnaissance des lettres"},
{id:"hebal_15",lv:"hebreu-alphabet",cat:"Alphabet",diff:2,q:"La lettre ר se prononce…",ch:["'R'","'L'","'M'","'N'"],ans:0,se:"ר est la lettre Resh, qui correspond au son 'R'.",pourquoi:"Lamed (ל) fait 'L', Mem (מ) fait 'M', Nun (נ) fait 'N'.",regle:"Resh (ר) = son 'R'.",sk:"Sons des lettres"},
{id:"hebal_16",lv:"hebreu-alphabet",cat:"Alphabet",diff:3,q:"Quelle lettre a la même forme que ב mais sans le point intérieur ?",ch:["Vet","Caf","Pé","Tsadi"],ans:0,se:"ב avec un point (dagesh) se prononce 'B' (Bet) ; sans point, c'est 'V' (Vet) — c'est la même lettre !",pourquoi:"Le point change la prononciation de Bet/Vet, Kaf/Khaf, Pe/Fe.",regle:"En hébreu, le dagesh (point) durcit la consonne : Bet/Vet, Kaf/Khaf, Pe/Fe.",sk:"Dagesh"},
{id:"hebal_17",lv:"hebreu-alphabet",cat:"Alphabet",diff:1,q:"La lettre nommée 'Dalet' s'écrit…",ch:["ד","ה","ו","ז"],ans:0,se:"ד est la lettre Dalet, 4e de l'alphabet, son 'D'.",pourquoi:"ה = Hé, ו = Vav, ז = Zayin.",regle:"Dalet (ד) = son 'D'.",sk:"Reconnaissance des lettres"},
{id:"hebal_18",lv:"hebreu-alphabet",cat:"Alphabet",diff:2,q:"Quel est le nom de la lettre ע ?",ch:["Alef","Ayin","Het","Khaf"],ans:1,se:"ע est la lettre Ayin. Elle est silencieuse en hébreu moderne (mais gutturale en hébreu ancien).",pourquoi:"Alef est א (souvent confondue avec Ayin par les débutants).",regle:"Ayin (ע) = lettre gutturale, généralement silencieuse aujourd'hui.",sk:"Reconnaissance des lettres"},
{id:"hebal_19",lv:"hebreu-alphabet",cat:"Alphabet",diff:3,q:"En hébreu biblique, les lettres servent aussi à…",ch:["Compter (valeurs numériques)","Faire de la musique","Dessiner","Cuisiner"],ans:0,se:"Chaque lettre a une valeur numérique (Alef=1, Bet=2, … Yod=10, … Tav=400). On appelle ça la guématria.",pourquoi:"À l'époque, il n'y avait pas de chiffres séparés en hébreu : on utilisait les lettres.",regle:"Guématria = chaque lettre = un nombre. Alef=1, Bet=2, Gimel=3...",sk:"Guématria"},
{id:"hebal_20",lv:"hebreu-alphabet",cat:"Alphabet",diff:2,q:"Quelle lettre est la 'jumelle' visuelle de Resh (ר) ?",ch:["Dalet (ד)","Mem (מ)","Vav (ו)","Tav (ת)"],ans:0,se:"ר (Resh) et ד (Dalet) se ressemblent beaucoup ! Résh est plus arrondi, Dalet a un coin droit en haut.",pourquoi:"Beaucoup d'élèves les confondent au début.",regle:"Astuce : Dalet a un angle droit (D pour Droit), Resh est arrondi (R pour Rond).",sk:"Distinguer les lettres similaires"}
);

EX.push(
/* ═══ HÉBREU — Vocabulaire de base ═══ */
{id:"hebvoc_01",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:1,q:"Que veut dire 'שלום' (Shalom) ?",ch:["Au revoir","Bonjour / Paix","Merci","Pardon"],ans:1,se:"Shalom signifie 'paix' et s'utilise pour dire bonjour ou au revoir. C'est le mot le plus connu en hébreu.",pourquoi:"Il sert à la fois pour saluer en arrivant ET en partant.",regle:"Shalom = bonjour, au revoir, paix.",sk:"Salutations"},
{id:"hebvoc_02",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:1,q:"Comment dit-on 'merci' en hébreu ?",ch:["Boker tov","Toda","Slikha","Bevakasha"],ans:1,se:"'Toda' (תודה) signifie merci. On peut dire 'Toda raba' pour 'merci beaucoup'.",pourquoi:"Boker tov = bonjour (matin), Slikha = pardon, Bevakasha = s'il vous plaît.",regle:"Toda = merci. Toda raba = merci beaucoup.",sk:"Politesse"},
{id:"hebvoc_03",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:1,q:"Que veut dire 'אבא' (Aba) ?",ch:["Maman","Papa","Frère","Sœur"],ans:1,se:"Aba (אבא) signifie 'papa'. Le mot maman se dit 'Ima' (אמא).",pourquoi:"Très facile à retenir car ça commence par Alef (א).",regle:"Aba = Papa, Ima = Maman.",sk:"Famille"},
{id:"hebvoc_04",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:1,q:"Comment dit-on 'oui' en hébreu ?",ch:["Lo","Ken","Toda","Mah"],ans:1,se:"'Ken' (כן) signifie 'oui'. Pour 'non', on dit 'Lo' (לא).",pourquoi:"Lo = non, Toda = merci, Mah = quoi.",regle:"Ken = oui, Lo = non.",sk:"Mots de base"},
{id:"hebvoc_05",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:2,q:"Que veut dire 'מים' (Mayim) ?",ch:["Pain","Eau","Lait","Vin"],ans:1,se:"Mayim (מים) signifie 'eau'. Mot très utile au quotidien.",pourquoi:"Lehem = pain, Halav = lait, Yayin = vin.",regle:"Mayim = eau. Lehem = pain. Halav = lait.",sk:"Aliments"},
{id:"hebvoc_06",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:2,q:"Comment dit-on 'bonjour le matin' en hébreu ?",ch:["Boker tov","Layla tov","Erev tov","Shabbat shalom"],ans:0,se:"'Boker tov' (בוקר טוב) signifie littéralement 'bon matin', utilisé pour bonjour le matin.",pourquoi:"Layla tov = bonne nuit, Erev tov = bonsoir.",regle:"Boker tov (matin), Erev tov (soir), Layla tov (nuit).",sk:"Salutations"},
{id:"hebvoc_07",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:1,q:"Que signifie 'אני' (Ani) ?",ch:["Tu","Je","Il","Elle"],ans:1,se:"Ani (אני) signifie 'je' / 'moi'.",pourquoi:"Ata (m) ou At (f) = tu, Hou = il, Hi = elle.",regle:"Pronoms : Ani (je), Ata/At (tu), Hou (il), Hi (elle).",sk:"Pronoms"},
{id:"hebvoc_08",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:2,q:"Que veut dire 'ספר' (Sefer) ?",ch:["Livre","Stylo","Table","Maison"],ans:0,se:"Sefer (ספר) signifie 'livre'. C'est un mot très important (Sefer Torah = livre de la Torah).",pourquoi:"Et (עט) = stylo, Shulkhan = table, Bayit = maison.",regle:"Sefer = livre. Pluriel : Sfarim (ספרים).",sk:"École"},
{id:"hebvoc_09",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:2,q:"Comment dit-on 'maison' en hébreu ?",ch:["Sefer","Bayit","Yom","Lehem"],ans:1,se:"Bayit (בית) signifie 'maison'. Bet ha-Sefer = maison du livre = école.",pourquoi:"Sefer = livre, Yom = jour, Lehem = pain.",regle:"Bayit = maison. Bet (en construction) = maison de…",sk:"Lieux"},
{id:"hebvoc_10",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:1,q:"Que signifie 'אחד' (Ehad) ?",ch:["Un","Deux","Trois","Quatre"],ans:0,se:"Ehad (אחד) = 1. Shtayim = 2, Shalosh = 3, Arba = 4.",pourquoi:"Pour les nombres, l'ordre est : Ehad, Shtayim, Shalosh, Arba, Hamesh.",regle:"1=Ehad, 2=Shtayim, 3=Shalosh, 4=Arba, 5=Hamesh.",sk:"Nombres"},
{id:"hebvoc_11",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:2,q:"Comment dit-on 'pardon' / 'excuse-moi' en hébreu ?",ch:["Toda","Shalom","Slikha","Boker tov"],ans:2,se:"Slikha (סליחה) signifie pardon, excuse-moi.",pourquoi:"Toda = merci, Shalom = bonjour/paix, Boker tov = bonjour matin.",regle:"Slikha = pardon. Toda = merci. Bevakasha = s'il vous plaît.",sk:"Politesse"},
{id:"hebvoc_12",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:2,q:"Que veut dire 'יום' (Yom) ?",ch:["Nuit","Jour","Semaine","Mois"],ans:1,se:"Yom (יום) signifie 'jour'. Yom shishi = vendredi (6e jour).",pourquoi:"Layla = nuit, Shavoua = semaine, Hodesh = mois.",regle:"Yom = jour. Layla = nuit. Shavoua = semaine.",sk:"Temps"},
{id:"hebvoc_13",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:1,q:"Comment dit-on 'maman' en hébreu ?",ch:["Aba","Ima","Ben","Bat"],ans:1,se:"Ima (אמא) = maman. Aba (אבא) = papa.",pourquoi:"Ben = fils, Bat = fille.",regle:"Famille : Aba (papa), Ima (maman), Ben (fils), Bat (fille).",sk:"Famille"},
{id:"hebvoc_14",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:3,q:"Que signifie 'תפוח' (Tapuah) ?",ch:["Pain","Pomme","Banane","Orange"],ans:1,se:"Tapuah (תפוח) = pomme. Tapuah adama (pomme de terre) = patate !",pourquoi:"Lehem = pain, Banana = banane (transparent), Tapuz = orange.",regle:"Tapuah = pomme. Tapuah adama = pomme de terre.",sk:"Fruits"},
{id:"hebvoc_15",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:2,q:"Comment dit-on 'soleil' en hébreu ?",ch:["Yareah","Shemesh","Kokhav","Shamayim"],ans:1,se:"Shemesh (שמש) = soleil.",pourquoi:"Yareah = lune, Kokhav = étoile, Shamayim = ciel.",regle:"Shemesh = soleil, Yareah = lune, Kokhav = étoile.",sk:"Nature"},
{id:"hebvoc_16",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:1,q:"Que veut dire 'כלב' (Kelev) ?",ch:["Chat","Chien","Cheval","Oiseau"],ans:1,se:"Kelev (כלב) = chien.",pourquoi:"Hatul = chat, Sus = cheval, Tsipor = oiseau.",regle:"Animaux : Kelev (chien), Hatul (chat), Sus (cheval), Tsipor (oiseau).",sk:"Animaux"},
{id:"hebvoc_17",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:2,q:"Comment dit-on 'ami' en hébreu ?",ch:["Haver","Sefer","Bayit","Yom"],ans:0,se:"Haver (חבר) = ami(e masculin). Havera (חברה) = amie (féminin).",pourquoi:"Sefer = livre, Bayit = maison, Yom = jour.",regle:"Haver = ami. Hevré (pluriel) = amis.",sk:"Personnes"},
{id:"hebvoc_18",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:3,q:"Que signifie 'מה שלומך' (Mah shlomkha) ?",ch:["Quel est ton nom ?","Comment vas-tu ?","Où vas-tu ?","Quel âge as-tu ?"],ans:1,se:"'Mah shlomkha?' = 'Comment vas-tu ?' (à un garçon). Pour une fille : 'Mah shlomekh?'.",pourquoi:"'Mah shimkha?' = quel est ton nom, 'Le-an?' = où vas-tu.",regle:"Mah shlomkha (à un garçon) / Mah shlomekh (à une fille) = comment vas-tu.",sk:"Phrases courantes"},
{id:"hebvoc_19",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:1,q:"Comment dit-on 'pain' en hébreu ?",ch:["Mayim","Lehem","Halav","Tapuah"],ans:1,se:"Lehem (לחם) = pain. Bet Lehem = Bethlehem = 'maison du pain'.",pourquoi:"Mayim = eau, Halav = lait, Tapuah = pomme.",regle:"Lehem = pain. Mayim = eau. Halav = lait.",sk:"Aliments"},
{id:"hebvoc_20",lv:"hebreu-vocabulaire",cat:"Vocabulaire",diff:2,q:"Que veut dire 'טוב' (Tov) ?",ch:["Mauvais","Bon / Bien","Grand","Petit"],ans:1,se:"Tov (טוב) = bon, bien. Boker tov = 'bon matin' = bonjour.",pourquoi:"Tov est un des mots les plus utilisés en hébreu.",regle:"Tov = bon/bien. Lo tov = pas bon.",sk:"Adjectifs"}
);

EX.push(
/* ═══ HÉBREU — Expressions courantes ═══ */
{id:"hebex_01",lv:"hebreu-expressions",cat:"Expressions",diff:1,q:"Que dit-on pour souhaiter un bon Shabbat ?",ch:["Hag sameah","Shabbat shalom","Mazal tov","Chag chameah"],ans:1,se:"'Shabbat shalom' = 'Shabbat de paix', salutation traditionnelle du vendredi soir au samedi.",pourquoi:"Hag sameah = bonne fête, Mazal tov = félicitations.",regle:"Shabbat shalom = bon Shabbat (vendredi-samedi).",sk:"Salutations religieuses"},
{id:"hebex_02",lv:"hebreu-expressions",cat:"Expressions",diff:2,q:"Que veut dire 'Mazal tov' ?",ch:["Bonne nuit","Félicitations","Au revoir","Bon appétit"],ans:1,se:"'Mazal tov' (מזל טוב) = 'bonne chance/bon destin', utilisé pour féliciter (mariage, naissance, anniversaire).",pourquoi:"Layla tov = bonne nuit, Lehitraot = au revoir, Be-teavon = bon appétit.",regle:"Mazal tov = félicitations. Très utilisé !",sk:"Félicitations"},
{id:"hebex_03",lv:"hebreu-expressions",cat:"Expressions",diff:2,q:"Comment dit-on 'au revoir' en hébreu ?",ch:["Shalom","Lehitraot","Toda","Slikha"],ans:1,se:"'Lehitraot' (להתראות) = 'au revoir' (littéralement 'à se revoir'). On peut aussi utiliser 'Shalom'.",pourquoi:"Shalom est correct mais plus général. Lehitraot est spécifique au revoir.",regle:"Lehitraot = au revoir. Bye = familier (utilisé aussi).",sk:"Salutations"},
{id:"hebex_04",lv:"hebreu-expressions",cat:"Expressions",diff:3,q:"Que veut dire 'Be-teavon' (בתאבון) ?",ch:["Bonne santé","Bon appétit","Bon voyage","Bonne année"],ans:1,se:"'Be-teavon' = 'avec appétit' = bon appétit, dit avant de manger.",pourquoi:"Bonne santé = La-briut. Bon voyage = Nesia tova.",regle:"Be-teavon = bon appétit. Avant le repas.",sk:"Repas"},
{id:"hebex_05",lv:"hebreu-expressions",cat:"Expressions",diff:2,q:"À tes souhaits' (quelqu'un éternue) se dit en hébreu :",ch:["Shalom","La-briut","Be-teavon","Toda"],ans:1,se:"'La-briut' (לבריאות) = 'à la santé', dit après un éternuement.",pourquoi:"Be-teavon = bon appétit (avant manger).",regle:"La-briut = à tes souhaits / à la santé.",sk:"Réactions"},
{id:"hebex_06",lv:"hebreu-expressions",cat:"Expressions",diff:1,q:"Comment dit-on 'bonne nuit' en hébreu ?",ch:["Boker tov","Erev tov","Layla tov","Shabbat shalom"],ans:2,se:"'Layla tov' (לילה טוב) = 'bonne nuit', dit avant d'aller dormir.",pourquoi:"Boker tov = bonjour matin, Erev tov = bonsoir.",regle:"Boker (matin) → Erev (soir) → Layla (nuit). Toujours suivi de 'tov'.",sk:"Salutations"},
{id:"hebex_07",lv:"hebreu-expressions",cat:"Expressions",diff:3,q:"'Eyn ba'aya' (אין בעיה) signifie…",ch:["C'est cassé","Pas de problème","Je ne sais pas","Je suis fatigué"],ans:1,se:"'Eyn ba'aya' = 'il n'y a pas de problème', équivalent de 'no problem' en anglais. Très utilisé.",pourquoi:"Expression du quotidien, utilisée pour rassurer ou accepter.",regle:"Eyn ba'aya = pas de problème.",sk:"Phrases du quotidien"},
{id:"hebex_08",lv:"hebreu-expressions",cat:"Expressions",diff:2,q:"Quand on entre dans une maison (chez quelqu'un), on dit souvent…",ch:["Shalom alei-khem","Toda raba","La-briut","Yom huledet sameah"],ans:0,se:"'Shalom alei-khem' (שלום עליכם) = 'paix sur vous', salutation traditionnelle pour entrer.",pourquoi:"La réponse traditionnelle est 'Alei-khem shalom' (et sur vous la paix).",regle:"Shalom alei-khem = paix sur vous (très traditionnel).",sk:"Salutations"},
{id:"hebex_09",lv:"hebreu-expressions",cat:"Expressions",diff:3,q:"'Yom huledet sameah' veut dire…",ch:["Bonne année","Joyeux anniversaire","Bonne fête","Bon Shabbat"],ans:1,se:"'Yom huledet sameah' (יום הולדת שמח) = 'joyeux jour de naissance' = joyeux anniversaire.",pourquoi:"Bonne année = Shana tova. Bonne fête = Hag sameah.",regle:"Yom huledet sameah = joyeux anniversaire.",sk:"Anniversaires"},
{id:"hebex_10",lv:"hebreu-expressions",cat:"Expressions",diff:2,q:"Pour souhaiter une bonne année (Roch Hachana), on dit…",ch:["Shabbat shalom","Shana tova","Mazal tov","Layla tov"],ans:1,se:"'Shana tova' (שנה טובה) = 'bonne année', dit pour Roch Hachana (nouvel an juif).",pourquoi:"Shabbat shalom = bon Shabbat, Mazal tov = félicitations.",regle:"Shana tova = bonne année.",sk:"Fêtes"},
{id:"hebex_11",lv:"hebreu-expressions",cat:"Expressions",diff:1,q:"Comment dit-on 's'il vous plaît' en hébreu ?",ch:["Toda","Bevakasha","Shalom","Slikha"],ans:1,se:"'Bevakasha' (בבקשה) = 's'il vous plaît' (et aussi 'de rien' en réponse à merci).",pourquoi:"Toda = merci, Slikha = pardon.",regle:"Bevakasha = s'il vous plaît + de rien.",sk:"Politesse"},
{id:"hebex_12",lv:"hebreu-expressions",cat:"Expressions",diff:3,q:"'Kol ha-kavod' (כל הכבוד) veut dire…",ch:["Bonjour","Bravo / Tout l'honneur","Adieu","Désolé"],ans:1,se:"'Kol ha-kavod' = 'tout l'honneur' = bravo, félicitations pour un effort accompli.",pourquoi:"Mazal tov = félicitations pour un événement (mariage, naissance). Kol ha-kavod = bravo pour un effort.",regle:"Kol ha-kavod = bravo (pour une réussite, un effort).",sk:"Encouragements"},
{id:"hebex_13",lv:"hebreu-expressions",cat:"Expressions",diff:2,q:"Pour Hanouka, on souhaite…",ch:["Hag sameah","Boker tov","Mazal tov","Lehitraot"],ans:0,se:"'Hag sameah' (חג שמח) = 'joyeuse fête', utilisé pour toutes les fêtes juives.",pourquoi:"Boker tov = bonjour, Mazal tov = félicitations.",regle:"Hag sameah = bonne fête (toutes fêtes juives).",sk:"Fêtes"},
{id:"hebex_14",lv:"hebreu-expressions",cat:"Expressions",diff:2,q:"Comment dit-on 'enchanté' (en rencontrant qqn) ?",ch:["Naim me'od","Toda raba","Shalom","Lehitraot"],ans:0,se:"'Naim me'od' (נעים מאוד) = 'très agréable' = enchanté.",pourquoi:"Toda raba = merci beaucoup.",regle:"Naim me'od = enchanté (lors d'une rencontre).",sk:"Présentations"},
{id:"hebex_15",lv:"hebreu-expressions",cat:"Expressions",diff:3,q:"'Ma nishma' (מה נשמע) signifie littéralement 'qu'entend-on' et s'utilise pour…",ch:["Demander l'heure","Dire 'quoi de neuf'","Saluer le matin","Demander pardon"],ans:1,se:"'Ma nishma' = 'quoi de neuf', façon familière de dire 'comment ça va'.",pourquoi:"Mah shlomkha = comment vas-tu (plus formel).",regle:"Ma nishma = quoi de neuf (familier).",sk:"Conversations"},
{id:"hebex_16",lv:"hebreu-expressions",cat:"Expressions",diff:2,q:"Que dit-on à quelqu'un qui part en voyage ?",ch:["Nesia tova","Shabbat shalom","Yom huledet sameah","Toda"],ans:0,se:"'Nesia tova' (נסיעה טובה) = 'bon voyage'.",pourquoi:"Shabbat shalom = bon Shabbat, Yom huledet sameah = joyeux anniversaire.",regle:"Nesia tova = bon voyage.",sk:"Voyage"},
{id:"hebex_17",lv:"hebreu-expressions",cat:"Expressions",diff:1,q:"Comment dit-on 'merci beaucoup' en hébreu ?",ch:["Toda","Toda raba","Bevakasha raba","Shalom raba"],ans:1,se:"'Toda raba' (תודה רבה) = 'merci beaucoup' ('raba' = grande/beaucoup).",pourquoi:"Toda seul = merci. Avec 'raba' = beaucoup.",regle:"Toda raba = merci beaucoup.",sk:"Politesse"},
{id:"hebex_18",lv:"hebreu-expressions",cat:"Expressions",diff:3,q:"'Be-ezrat ha-Shem' (בעזרת השם) veut dire…",ch:["Au revoir","Avec l'aide de Dieu, si Dieu le veut","À toute vitesse","Pardon"],ans:1,se:"'Be-ezrat ha-Shem' = 'avec l'aide de Dieu', utilisé pour exprimer un espoir ou une intention (équivalent du 'inch'Allah' arabe).",pourquoi:"Expression religieuse très courante en hébreu.",regle:"Be-ezrat ha-Shem = avec l'aide de Dieu / si Dieu le veut.",sk:"Expressions religieuses"},
{id:"hebex_19",lv:"hebreu-expressions",cat:"Expressions",diff:2,q:"Pour féliciter quelqu'un qui se marie, on dit…",ch:["Mazal tov","Layla tov","La-briut","Shana tova"],ans:0,se:"'Mazal tov' = félicitations, parfait pour un mariage, une naissance, une réussite.",pourquoi:"Layla tov = bonne nuit, La-briut = à tes souhaits.",regle:"Mazal tov = félicitations (mariage, naissance, anniversaire, réussite).",sk:"Félicitations"},
{id:"hebex_20",lv:"hebreu-expressions",cat:"Expressions",diff:2,q:"'Ahalan' (אהלן) est un mot familier pour dire…",ch:["Au revoir","Salut !","Pardon","Merci"],ans:1,se:"'Ahalan' vient de l'arabe et est utilisé en hébreu israélien comme 'Salut !' (familier).",pourquoi:"Forme très familière, surtout entre amis ou jeunes.",regle:"Ahalan = salut (familier, très utilisé en Israël).",sk:"Salutations familières"}
);

EX.push(
/* ═══ HÉBREU — Lecture mots et phrases ═══ */
{id:"heblec_01",lv:"hebreu-lecture",cat:"Lecture",diff:1,q:"Comment se prononce le mot שלום ?",ch:["Shalom","Tovel","Lomah","Shalov"],ans:0,se:"שלום se lit Shin-Lamed-Vav-Mem (de droite à gauche) = SHALOM.",pourquoi:"Lecture de droite à gauche : ש (Sh), ל (l), ו (o), ם (m).",regle:"Lire de droite à gauche : ש (Sh) → ל (l) → ו (o) → ם (m) = Shalom.",sk:"Lecture de mots"},
{id:"heblec_02",lv:"hebreu-lecture",cat:"Lecture",diff:1,q:"Comment se prononce אבא ?",ch:["Aba","Bha","Baal","Abba"],ans:0,se:"אבא = Alef-Bet-Alef = ABA. Le 1er Alef porte la voyelle 'A', puis Bet 'B', puis Alef 'A' final.",pourquoi:"Lecture de droite à gauche : א (a) → ב (b) → א (a).",regle:"Aba = papa.",sk:"Lecture de mots"},
{id:"heblec_03",lv:"hebreu-lecture",cat:"Lecture",diff:2,q:"Comment se lit אמא ?",ch:["Ima","Ama","Mai","Aim"],ans:0,se:"אמא = Alef-Mem-Alef = IMA (avec voyelles : 'i' sur Alef puis 'a' sur Mem).",pourquoi:"En hébreu, les voyelles ne sont pas toujours écrites. On les déduit du contexte ou de petits points (nikud).",regle:"Ima = maman.",sk:"Voyelles cachées"},
{id:"heblec_04",lv:"hebreu-lecture",cat:"Lecture",diff:2,q:"Le mot ספר se prononce…",ch:["Sefer","Pser","Refes","Spar"],ans:0,se:"ספר = Samekh-Pe-Resh = SEFER (livre).",pourquoi:"Lecture de droite à gauche : ס (s) → פ (f, ici sans dagesh) → ר (r).",regle:"Sefer = livre.",sk:"Lecture de mots"},
{id:"heblec_05",lv:"hebreu-lecture",cat:"Lecture",diff:2,q:"Comment se lit le mot כן ?",ch:["Ken","Nak","Khan","Kan"],ans:0,se:"כן = Kaf-Nun = KEN (oui).",pourquoi:"Court mot très utile : Ken (oui).",regle:"Ken = oui.",sk:"Lecture de mots courts"},
{id:"heblec_06",lv:"hebreu-lecture",cat:"Lecture",diff:1,q:"Le mot לא se lit…",ch:["Al","La","Lo","Ola"],ans:2,se:"לא = Lamed-Alef = LO (non). L'Alef est silencieuse, le Lamed porte le son 'O'.",pourquoi:"Lecture de droite à gauche : ל (l avec o) → א (silencieux) = Lo.",regle:"Lo = non.",sk:"Lecture de mots courts"},
{id:"heblec_07",lv:"hebreu-lecture",cat:"Lecture",diff:3,q:"Le mot ירושלים se prononce…",ch:["Yerushalayim","Roushalim","Yerusalem","Yim-shla-rou"],ans:0,se:"ירושלים = Yod-Resh-Vav-Shin-Lamed-Yod-Mem = YERUSHALAYIM (Jérusalem).",pourquoi:"Long mot, mais c'est l'un des plus connus : Jérusalem.",regle:"Yerushalayim = Jérusalem.",sk:"Lecture de mots longs"},
{id:"heblec_08",lv:"hebreu-lecture",cat:"Lecture",diff:2,q:"Comment se lit מים ?",ch:["Mayim","Im","Mim","Mami"],ans:0,se:"מים = Mem-Yod-Mem = MAYIM (eau). Notez : 2 lettres Mem (la 2e est finale ם).",pourquoi:"Mots simples avec lettres répétées : Mayim, Yamim (jours).",regle:"Mayim = eau.",sk:"Lecture de mots"},
{id:"heblec_09",lv:"hebreu-lecture",cat:"Lecture",diff:2,q:"Le mot טוב se prononce…",ch:["Tov","Bot","Vot","Otv"],ans:0,se:"טוב = Tet-Vav-Bet = TOV (bon, bien).",pourquoi:"Lecture de droite à gauche : ט (t) → ו (o) → ב (v).",regle:"Tov = bon, bien.",sk:"Lecture de mots"},
{id:"heblec_10",lv:"hebreu-lecture",cat:"Lecture",diff:3,q:"Comment se prononce le mot תורה ?",ch:["Torah","Hatorh","Roth","Toura"],ans:0,se:"תורה = Tav-Vav-Resh-Hé = TORAH (loi, Pentateuque).",pourquoi:"Mot très important du judaïsme.",regle:"Torah = loi écrite, les 5 livres de Moïse.",sk:"Mots religieux"},
{id:"heblec_11",lv:"hebreu-lecture",cat:"Lecture",diff:2,q:"Le mot בית se prononce…",ch:["Bayit","Tibet","Itba","Beit"],ans:0,se:"בית = Bet-Yod-Tav = BAYIT (maison). 'Yod' aide à former le son 'A-i'.",pourquoi:"On peut aussi dire 'Beit' (forme construite : Beit Lehem = Bethlehem).",regle:"Bayit = maison. Beit = maison de... (forme construite).",sk:"Lecture de mots"},
{id:"heblec_12",lv:"hebreu-lecture",cat:"Lecture",diff:1,q:"Comment se lit אחד ?",ch:["Ehad","Dahe","Hach","Ahed"],ans:0,se:"אחד = Alef-Het-Dalet = EHAD (un, le nombre 1).",pourquoi:"Lecture de droite à gauche : א (e) → ח (h) → ד (d).",regle:"Ehad = 1 (premier nombre).",sk:"Nombres"},
{id:"heblec_13",lv:"hebreu-lecture",cat:"Lecture",diff:3,q:"Le mot שבת se lit…",ch:["Shabbat","Tabbat","Bashash","Shavet"],ans:0,se:"שבת = Shin-Bet-Tav = SHABBAT (le 7e jour de la semaine, jour de repos).",pourquoi:"Mot très connu dans la culture juive.",regle:"Shabbat = jour de repos hebdomadaire (samedi).",sk:"Mots religieux"},
{id:"heblec_14",lv:"hebreu-lecture",cat:"Lecture",diff:2,q:"Comment se prononce תודה ?",ch:["Toda","Hoda","Dohat","Tadah"],ans:0,se:"תודה = Tav-Vav-Dalet-Hé = TODA (merci).",pourquoi:"Lecture de droite à gauche : ת (t) → ו (o) → ד (d) → ה (a finale).",regle:"Toda = merci.",sk:"Politesse"},
{id:"heblec_15",lv:"hebreu-lecture",cat:"Lecture",diff:2,q:"Le mot כלב se prononce…",ch:["Kelev","Belek","Lakev","Velek"],ans:0,se:"כלב = Kaf-Lamed-Bet = KELEV (chien).",pourquoi:"Lecture de droite à gauche : כ (k) → ל (l) → ב (v).",regle:"Kelev = chien.",sk:"Animaux"},
{id:"heblec_16",lv:"hebreu-lecture",cat:"Lecture",diff:3,q:"La phrase שלום עליכם se prononce…",ch:["Shalom alei-khem","Hem-eli-malosh","Olam-shevkim","Sha-omle-khem"],ans:0,se:"שלום עליכם = Shalom alei-khem (paix sur vous).",pourquoi:"Phrase composée de 2 mots : Shalom + alei-khem.",regle:"Shalom alei-khem = paix sur vous.",sk:"Lecture de phrases"},
{id:"heblec_17",lv:"hebreu-lecture",cat:"Lecture",diff:2,q:"Le mot אני se lit…",ch:["Ani","Ina","Niy","Yan"],ans:0,se:"אני = Alef-Nun-Yod = ANI (je, moi).",pourquoi:"Lecture de droite à gauche : א (a) → נ (n) → י (i).",regle:"Ani = je, moi.",sk:"Pronoms"},
{id:"heblec_18",lv:"hebreu-lecture",cat:"Lecture",diff:3,q:"Comment se prononce לחם ?",ch:["Lehem","Mehel","Khel","Helam"],ans:0,se:"לחם = Lamed-Het-Mem = LEHEM (pain). 'Bet Lehem' = Bethlehem ('maison du pain').",pourquoi:"Le 'Het' a un son guttural (raclement de gorge).",regle:"Lehem = pain.",sk:"Aliments"},
{id:"heblec_19",lv:"hebreu-lecture",cat:"Lecture",diff:2,q:"Le mot ילד se prononce…",ch:["Yeled","Dely","Edly","Yad"],ans:0,se:"ילד = Yod-Lamed-Dalet = YELED (garçon, enfant).",pourquoi:"Yalda (ילדה) = fille.",regle:"Yeled = garçon. Yalda = fille.",sk:"Personnes"},
{id:"heblec_20",lv:"hebreu-lecture",cat:"Lecture",diff:3,q:"La phrase אני אוהב אותך se prononce…",ch:["Ani ohev otkha","Otkha ohev ani","Ohev ani otkha","Tokha ani ohev"],ans:0,se:"אני אוהב אותך = Ani ohev otkha = 'Je t'aime' (à un garçon). À une fille : Ani ohev otakh.",pourquoi:"Lecture mot par mot, de droite à gauche : Ani (je) + Ohev (aime) + Otkha (toi-masc).",regle:"Ani ohev otkha (à un homme) / Ani ohev otakh (à une femme) = je t'aime.",sk:"Phrases d'amour"}
);

EX.push(
/* ═══ HISTOIRE CE2 — Préhistoire / Antiquité / Romains ═══ */
{id:"hi2_01",lv:"histoire-ce2",cat:"Préhistoire",diff:1,q:"Comment s'appelait l'homme préhistorique qui chassait les mammouths ?",ch:["Homo sapiens (et Néandertal)","Homo gigantus","Homo aquaticus","Homo zombicus"],ans:0,se:"Homo sapiens et Homo Néandertal vivaient à la Préhistoire et chassaient les mammouths.",pourquoi:"Homo sapiens est notre espèce. Néandertal a vécu en parallèle pendant longtemps.",regle:"Préhistoire = avant l'écriture. Hommes : Néandertal puis Homo sapiens.",sk:"Hommes préhistoriques"},
{id:"hi2_02",lv:"histoire-ce2",cat:"Préhistoire",diff:1,q:"Quelle est la plus grande invention du Paléolithique ?",ch:["La roue","Le feu","Le téléphone","L'avion"],ans:1,se:"La maîtrise du feu, vers –400 000 ans, a tout changé : cuisson, chaleur, protection.",pourquoi:"La roue date du Néolithique (plus tard). Téléphone et avion sont modernes.",regle:"Paléolithique : feu maîtrisé, outils en pierre taillée, chasse-cueillette.",sk:"Paléolithique"},
{id:"hi2_03",lv:"histoire-ce2",cat:"Préhistoire",diff:2,q:"Au Néolithique, l'homme devient…",ch:["Chasseur-cueilleur","Agriculteur et éleveur sédentaire","Marchand de glaces","Astronaute"],ans:1,se:"Au Néolithique (~–10 000 ans), l'homme commence l'agriculture et l'élevage : il se sédentarise.",pourquoi:"Au Paléolithique, il était chasseur-cueilleur nomade.",regle:"Néolithique = pierre polie + agriculture + élevage + sédentarisation.",sk:"Néolithique"},
{id:"hi2_04",lv:"histoire-ce2",cat:"Préhistoire",diff:2,q:"Les peintures de la grotte de Lascaux représentent surtout…",ch:["Des dinosaures","Des animaux (taureaux, chevaux)","Des voitures","Des avions"],ans:1,se:"Les hommes préhistoriques peignaient des animaux (chevaux, taureaux, cerfs) avec des pigments naturels.",pourquoi:"Les dinosaures avaient disparu bien avant l'apparition de l'homme (–65 millions d'années).",regle:"Lascaux (Dordogne) = peintures préhistoriques d'animaux, ~–17 000 ans.",sk:"Art préhistorique"},
{id:"hi2_05",lv:"histoire-ce2",cat:"Antiquité",diff:1,q:"Quand commence l'Antiquité ?",ch:["Avec l'invention du feu","Avec l'invention de l'écriture (~3500 av. J.-C.)","Avec l'an 0","Au Moyen Âge"],ans:1,se:"L'Antiquité commence avec l'invention de l'écriture (vers –3500), en Mésopotamie (Sumer).",pourquoi:"Préhistoire = avant l'écriture, Antiquité = après.",regle:"L'écriture = naissance de l'Histoire (au sens strict).",sk:"Périodes historiques"},
{id:"hi2_06",lv:"histoire-ce2",cat:"Antiquité",diff:2,q:"Les Égyptiens ont construit…",ch:["La Tour Eiffel","Les pyramides","Le château de Versailles","Le Stade de France"],ans:1,se:"Les Égyptiens ont construit les pyramides comme tombeaux pour leurs pharaons (Khéops, Khephren…).",pourquoi:"La Tour Eiffel et Versailles sont français, le Stade de France est moderne.",regle:"Pyramides d'Égypte = tombeaux des pharaons, ~–2500.",sk:"Égypte antique"},
{id:"hi2_07",lv:"histoire-ce2",cat:"Antiquité",diff:1,q:"Qui dirigeait l'Égypte antique ?",ch:["Le roi","Le pharaon","Le président","Le chef indien"],ans:1,se:"Le pharaon est le souverain d'Égypte, considéré comme un dieu vivant.",pourquoi:"Roi est un terme général ; pharaon est spécifique à l'Égypte.",regle:"Pharaon = chef d'Égypte (politique + religieux).",sk:"Vocabulaire Antiquité"},
{id:"hi2_08",lv:"histoire-ce2",cat:"Antiquité",diff:2,q:"Les Gaulois étaient…",ch:["Des Romains","Des Celtes vivant en Gaule (≈ France)","Des Égyptiens","Des Vikings"],ans:1,se:"Les Gaulois étaient des peuples celtes qui vivaient en Gaule (territoire de la France actuelle).",pourquoi:"Les Romains ont conquis la Gaule sous Jules César.",regle:"Gaule = territoire français/belge avant la conquête romaine. Habitants = Gaulois (celtes).",sk:"Gaulois"},
{id:"hi2_09",lv:"histoire-ce2",cat:"Antiquité",diff:2,q:"Qui a vaincu Vercingétorix à Alésia ?",ch:["Napoléon","Jules César","Charlemagne","Louis XIV"],ans:1,se:"En –52, Jules César a vaincu Vercingétorix (chef gaulois) à Alésia. La Gaule devient romaine.",pourquoi:"Napoléon, Charlemagne, Louis XIV sont d'autres époques.",regle:"–52 av. J.-C. : bataille d'Alésia, défaite de Vercingétorix face à Jules César.",sk:"Conquête de la Gaule"},
{id:"hi2_10",lv:"histoire-ce2",cat:"Antiquité",diff:2,q:"Que signifie 'av. J.-C.' ?",ch:["Avant Jésus-Christ","Avenue Jean-Claude","À voir Janvier-Chez","Avant Janvier"],ans:0,se:"'Av. J.-C.' = 'avant Jésus-Christ'. La naissance de Jésus est le repère de notre calendrier (an 1).",pourquoi:"Tout ce qui précède la naissance de Jésus est noté avec av. J.-C., et le nombre diminue plus on remonte.",regle:"Avant Jésus-Christ (av. J.-C.) = chiffre qui DIMINUE avec le temps. Après J.-C. = chiffre qui AUGMENTE.",sk:"Calendrier"},
{id:"hi2_11",lv:"histoire-ce2",cat:"Antiquité",diff:3,q:"Quelle invention romaine permet d'avoir l'eau dans les villes ?",ch:["L'aqueduc","Le télégraphe","Le métro","La voiture"],ans:0,se:"Les aqueducs romains transportaient l'eau sur des dizaines de kilomètres jusqu'aux villes (ex : Pont du Gard).",pourquoi:"Télégraphe, métro, voiture : tous bien plus tardifs.",regle:"Romains = aqueducs, routes pavées, ponts, thermes, théâtres.",sk:"Inventions romaines"},
{id:"hi2_12",lv:"histoire-ce2",cat:"Antiquité",diff:1,q:"Comment s'appelait la capitale de l'Empire romain ?",ch:["Paris","Athènes","Rome","Le Caire"],ans:2,se:"Rome est la capitale de l'Empire romain. Encore aujourd'hui, c'est la capitale de l'Italie.",pourquoi:"Athènes était la grande cité grecque ; Le Caire est en Égypte.",regle:"Empire romain → capitale Rome.",sk:"Géographie antique"},
{id:"hi2_13",lv:"histoire-ce2",cat:"Préhistoire",diff:1,q:"Le mammouth était un animal préhistorique ressemblant à…",ch:["Une girafe","Un éléphant poilu","Un dinosaure","Un poisson"],ans:1,se:"Le mammouth était une sorte d'éléphant à longue toison (poils), adapté au froid de l'ère glaciaire.",pourquoi:"Les dinosaures avaient disparu bien avant le mammouth.",regle:"Mammouth = grand mammifère préhistorique poilu, disparu il y a ~10 000 ans.",sk:"Animaux préhistoriques"},
{id:"hi2_14",lv:"histoire-ce2",cat:"Antiquité",diff:2,q:"Quelle ville romaine a été détruite par l'éruption du Vésuve en 79 ap. J.-C. ?",ch:["Athènes","Pompéi","Carthage","Lutèce"],ans:1,se:"Pompéi a été ensevelie sous les cendres en 79 ap. J.-C., conservant intacte une ville romaine entière.",pourquoi:"Lutèce était la Paris romaine ; Carthage était phénicienne.",regle:"Pompéi = ville romaine ensevelie en 79 ap. J.-C. (Vésuve, Italie).",sk:"Catastrophes antiques"},
{id:"hi2_15",lv:"histoire-ce2",cat:"Antiquité",diff:3,q:"Que faisaient les gladiateurs ?",ch:["Ils écrivaient des livres","Ils combattaient dans les arènes (Colisée)","Ils gouvernaient","Ils faisaient du commerce"],ans:1,se:"Les gladiateurs étaient des combattants (souvent esclaves) qui s'affrontaient dans les arènes pour distraire le peuple.",pourquoi:"Le Colisée à Rome est l'arène la plus célèbre.",regle:"Gladiateurs = combattants des jeux du cirque romain.",sk:"Société romaine"},
{id:"hi2_16",lv:"histoire-ce2",cat:"Préhistoire",diff:2,q:"L'agriculture est apparue il y a environ…",ch:["100 ans","1 000 ans","10 000 ans","1 million d'années"],ans:2,se:"L'agriculture est née au Néolithique, il y a environ 10 000 ans (8000 av. J.-C.).",pourquoi:"Le passage de chasseur-cueilleur à agriculteur est une révolution.",regle:"Néolithique → début de l'agriculture (~–10 000 ans).",sk:"Repères chronologiques"},
{id:"hi2_17",lv:"histoire-ce2",cat:"Antiquité",diff:1,q:"De quel peuple Astérix est-il un héros (de bande dessinée) ?",ch:["Romain","Gaulois","Égyptien","Grec"],ans:1,se:"Astérix est un guerrier gaulois, du petit village d'Armorique, qui résiste aux Romains.",pourquoi:"Sa potion magique et son ami Obélix sont gaulois.",regle:"Astérix = Gaulois ! Les BD de Goscinny/Uderzo se passent en –50 av. J.-C.",sk:"Culture populaire"},
{id:"hi2_18",lv:"histoire-ce2",cat:"Antiquité",diff:3,q:"Qui était Cléopâtre ?",ch:["Une reine d'Égypte","Une déesse romaine","Une princesse française","Une chanteuse"],ans:0,se:"Cléopâtre VII fut la dernière reine d'Égypte (~–69 à –30 av. J.-C.). Elle a connu Jules César et Marc Antoine.",pourquoi:"Elle était d'origine grecque (dynastie ptolémaïque) mais reine d'Égypte.",regle:"Cléopâtre = dernière reine d'Égypte, ~–30 av. J.-C.",sk:"Personnages antiques"},
{id:"hi2_19",lv:"histoire-ce2",cat:"Préhistoire",diff:2,q:"L'écriture cunéiforme est apparue chez les…",ch:["Sumériens (Mésopotamie)","Vikings","Aztèques","Inuits"],ans:0,se:"L'écriture cunéiforme (sur tablettes d'argile) est née à Sumer (Mésopotamie, actuelle Irak) vers –3500.",pourquoi:"Première écriture connue de l'humanité.",regle:"Premières écritures : Sumer (cunéiforme), Égypte (hiéroglyphes), Chine.",sk:"Naissance de l'écriture"},
{id:"hi2_20",lv:"histoire-ce2",cat:"Antiquité",diff:2,q:"Combien de temps a duré l'Empire romain (de sa fondation à sa chute) ?",ch:["Environ 100 ans","Environ 500 ans","Environ 1000 ans","10 000 ans"],ans:2,se:"L'Empire romain a duré environ 1000 ans (de –27 à 476 ap. J.-C. pour l'Empire d'Occident).",pourquoi:"C'est une civilisation très longue, qui a marqué profondément l'Europe.",regle:"Empire romain : ~1000 ans. Chute de Rome (476 ap. J.-C.) = fin de l'Antiquité.",sk:"Durée des civilisations"}
);

EX.push(
/* ═══ HISTOIRE CM1 — Moyen Âge / Renaissance ═══ */
{id:"hi1_01",lv:"histoire-cm1",cat:"Moyen Âge",diff:1,q:"Quand commence le Moyen Âge ?",ch:["En l'an 1000","À la chute de Rome (476)","En 1789","En 1492"],ans:1,se:"Le Moyen Âge commence avec la chute de l'Empire romain d'Occident en 476 ap. J.-C.",pourquoi:"Il finit en 1492 (découverte de l'Amérique) ou 1453 (chute de Constantinople).",regle:"Moyen Âge : 476 → ~1492 (1000 ans).",sk:"Périodes historiques"},
{id:"hi1_02",lv:"histoire-cm1",cat:"Moyen Âge",diff:2,q:"Qui était Charlemagne ?",ch:["Un roi gaulois","Un empereur couronné en l'an 800","Un viking","Un président"],ans:1,se:"Charlemagne fut couronné empereur d'Occident le 25 décembre 800. Il a unifié une grande partie de l'Europe.",pourquoi:"On l'appelle aussi Charles Ier ou Carolus Magnus.",regle:"Charlemagne = empereur des Francs et Lombards, couronné en 800.",sk:"Rois et empereurs"},
{id:"hi1_03",lv:"histoire-cm1",cat:"Moyen Âge",diff:2,q:"Les Vikings venaient de…",ch:["Espagne","Scandinavie (Norvège, Suède, Danemark)","Égypte","Chine"],ans:1,se:"Les Vikings étaient des peuples scandinaves (VIIIe-XIe siècles) qui ont navigué et commercé loin.",pourquoi:"Ils ont fondé la Normandie en France (les 'hommes du Nord').",regle:"Vikings = peuples scandinaves, navigateurs et guerriers.",sk:"Peuples du Moyen Âge"},
{id:"hi1_04",lv:"histoire-cm1",cat:"Moyen Âge",diff:1,q:"Le seigneur du Moyen Âge habitait dans un…",ch:["Appartement","Château fort","Hôtel","Camping"],ans:1,se:"Au Moyen Âge, les seigneurs habitaient dans des châteaux forts (donjon, remparts, douves) pour se protéger.",pourquoi:"Les paysans habitaient des maisons en bois et torchis dans le village.",regle:"Château fort = résidence et forteresse du seigneur féodal.",sk:"Société féodale"},
{id:"hi1_05",lv:"histoire-cm1",cat:"Moyen Âge",diff:2,q:"Au Moyen Âge, qui combat à cheval avec une armure ?",ch:["Le paysan","Le moine","Le chevalier","Le marchand"],ans:2,se:"Le chevalier était un guerrier noble qui combattait à cheval, en armure, et faisait serment de fidélité au seigneur.",pourquoi:"Devenir chevalier passait par l'adoubement.",regle:"Chevalier = guerrier noble à cheval, lié au seigneur par le serment de vassalité.",sk:"Société féodale"},
{id:"hi1_06",lv:"histoire-cm1",cat:"Moyen Âge",diff:2,q:"La majorité des paysans du Moyen Âge étaient…",ch:["Riches","Serfs (peu libres)","Voyageurs","Soldats"],ans:1,se:"La plupart étaient serfs : ils travaillaient les terres du seigneur et n'étaient pas vraiment libres.",pourquoi:"Une minorité de paysans étaient 'libres' (vilains) mais devaient quand même des taxes.",regle:"Serf = paysan attaché à la terre du seigneur, pas tout à fait libre.",sk:"Société paysanne"},
{id:"hi1_07",lv:"histoire-cm1",cat:"Moyen Âge",diff:3,q:"Qui était Jeanne d'Arc ?",ch:["Une reine","Une bergère qui a aidé Charles VII contre les Anglais","Une chanteuse","Une nonne célèbre"],ans:1,se:"Jeanne d'Arc (1412–1431), bergère de Domrémy, a libéré Orléans en 1429 et fait sacrer Charles VII roi à Reims.",pourquoi:"Elle a été brûlée à Rouen par les Anglais en 1431. Canonisée en 1920.",regle:"Jeanne d'Arc = héroïne de la Guerre de Cent Ans (1337-1453).",sk:"Personnages du Moyen Âge"},
{id:"hi1_08",lv:"histoire-cm1",cat:"Moyen Âge",diff:2,q:"Que sont les Croisades ?",ch:["Des fêtes","Des expéditions militaires chrétiennes pour reconquérir Jérusalem","Des courses à cheval","Des marchés"],ans:1,se:"Les Croisades (XIe-XIIIe s.) étaient des expéditions militaires lancées par les chrétiens pour récupérer la Terre Sainte (Jérusalem).",pourquoi:"Il y a eu 8 grandes Croisades.",regle:"Croisades = guerres religieuses entre chrétiens et musulmans pour Jérusalem (1095-1291).",sk:"Croisades"},
{id:"hi1_09",lv:"histoire-cm1",cat:"Moyen Âge",diff:1,q:"Quelle invention du Moyen Âge a révolutionné la diffusion des livres ?",ch:["Le téléphone","L'imprimerie de Gutenberg (~1450)","La télévision","La photo"],ans:1,se:"Vers 1450, Gutenberg invente l'imprimerie à caractères mobiles → les livres deviennent moins chers et plus diffusés.",pourquoi:"Avant, les livres étaient copiés à la main par des moines (très lent, très cher).",regle:"Imprimerie de Gutenberg ~1450 → diffusion massive des livres.",sk:"Inventions"},
{id:"hi1_10",lv:"histoire-cm1",cat:"Renaissance",diff:1,q:"Quand commence la Renaissance ?",ch:["Au XIVe-XVe siècle (Italie)","En 1789","En 1914","En l'an 0"],ans:0,se:"La Renaissance naît en Italie aux XIVe-XVe siècles, puis se diffuse en Europe au XVIe siècle.",pourquoi:"Elle marque la fin du Moyen Âge et le début des Temps modernes.",regle:"Renaissance = redécouverte de l'Antiquité, art, sciences (XIVe-XVIe s.).",sk:"Renaissance"},
{id:"hi1_11",lv:"histoire-cm1",cat:"Renaissance",diff:2,q:"Léonard de Vinci était…",ch:["Roi","Peintre, savant et inventeur italien","Pape","Musicien"],ans:1,se:"Léonard de Vinci (1452-1519) était à la fois peintre (Joconde), savant, inventeur, ingénieur. Génie universel de la Renaissance.",pourquoi:"Il a passé la fin de sa vie en France, invité par François Ier (Amboise).",regle:"Léonard de Vinci = génie de la Renaissance italienne.",sk:"Personnages de la Renaissance"},
{id:"hi1_12",lv:"histoire-cm1",cat:"Renaissance",diff:2,q:"Qui peint la Joconde ?",ch:["Picasso","Léonard de Vinci","Monet","Van Gogh"],ans:1,se:"La Joconde (Mona Lisa) a été peinte par Léonard de Vinci vers 1503-1506. Elle est exposée au Louvre.",pourquoi:"Picasso, Monet, Van Gogh sont d'autres époques (XIXe-XXe siècle).",regle:"La Joconde = Léonard de Vinci, ~1503.",sk:"Œuvres célèbres"},
{id:"hi1_13",lv:"histoire-cm1",cat:"Renaissance",diff:2,q:"Quel roi français est associé à la Renaissance et aux châteaux de la Loire ?",ch:["Louis XIV","François Ier","Henri IV","Napoléon"],ans:1,se:"François Ier (1494-1547) a fait construire/aménager Chambord, Blois, Amboise. Il invite Léonard de Vinci.",pourquoi:"Louis XIV est plus tardif (XVIIe s.) et associé à Versailles.",regle:"François Ier = roi de la Renaissance, mécène, châteaux de la Loire.",sk:"Rois de France"},
{id:"hi1_14",lv:"histoire-cm1",cat:"Renaissance",diff:3,q:"Que découvre Christophe Colomb en 1492 ?",ch:["L'Australie","L'Amérique","La Lune","L'Inde"],ans:1,se:"Le 12 octobre 1492, Christophe Colomb arrive en Amérique (croyant être en Inde !). C'est la fin du Moyen Âge.",pourquoi:"Il pensait avoir atteint l'Inde par l'Ouest, d'où le nom 'Indiens' donné aux peuples d'Amérique.",regle:"1492 = découverte de l'Amérique par Christophe Colomb. Marque la fin du Moyen Âge.",sk:"Grandes découvertes"},
{id:"hi1_15",lv:"histoire-cm1",cat:"Renaissance",diff:3,q:"Quelle théorie a défendu Galilée ?",ch:["La Terre est plate","La Terre tourne autour du Soleil","La Lune est faite de fromage","Les avions volent"],ans:1,se:"Galilée (1564-1642), savant italien, a défendu l'héliocentrisme (Terre tourne autour du Soleil), à la suite de Copernic.",pourquoi:"L'Église l'a condamné. 'E pur si muove' ('et pourtant elle tourne').",regle:"Héliocentrisme : Soleil au centre. Défendu par Copernic puis Galilée.",sk:"Sciences à la Renaissance"},
{id:"hi1_16",lv:"histoire-cm1",cat:"Moyen Âge",diff:2,q:"En 1066, qui conquiert l'Angleterre ?",ch:["Charlemagne","Guillaume le Conquérant (duc de Normandie)","Napoléon","Jules César"],ans:1,se:"Guillaume le Conquérant, duc de Normandie, gagne la bataille d'Hastings en 1066 et devient roi d'Angleterre.",pourquoi:"C'est pourquoi le français a fortement influencé l'anglais.",regle:"1066 = bataille d'Hastings, conquête normande de l'Angleterre.",sk:"Dates clés"},
{id:"hi1_17",lv:"histoire-cm1",cat:"Moyen Âge",diff:1,q:"Quelle religion domine en Europe au Moyen Âge ?",ch:["Hindouisme","Christianisme","Bouddhisme","Athéisme"],ans:1,se:"Le christianisme est la religion dominante en Europe au Moyen Âge. L'Église a un pouvoir énorme.",pourquoi:"L'Islam dominait au Moyen-Orient et en Afrique du Nord.",regle:"Europe médiévale = chrétienne, dirigée par le Pape (autorité religieuse).",sk:"Religion au Moyen Âge"},
{id:"hi1_18",lv:"histoire-cm1",cat:"Moyen Âge",diff:3,q:"Que sont les cathédrales gothiques ?",ch:["Des forteresses","De grandes églises avec voûtes pointues, grandes fenêtres","Des grottes","Des palais romains"],ans:1,se:"À partir du XIIe s., on construit des cathédrales gothiques (Chartres, Notre-Dame de Paris) avec voûtes en ogive et vitraux.",pourquoi:"Avant, le style était roman (plus massif, fenêtres petites).",regle:"Roman = XIe-XIIe s. (massif). Gothique = XIIe-XVe s. (élancé, vitraux).",sk:"Architecture médiévale"},
{id:"hi1_19",lv:"histoire-cm1",cat:"Renaissance",diff:2,q:"Quelle invention permet aux navigateurs de la Renaissance de s'orienter en mer ?",ch:["La radio","La boussole (et l'astrolabe)","Le GPS","Le smartphone"],ans:1,se:"La boussole (importée de Chine) et l'astrolabe permettent aux navigateurs de se repérer en pleine mer.",pourquoi:"GPS et smartphones sont du XXe-XXIe siècle.",regle:"Boussole = aiguille magnétique, indique le Nord. Inventée en Chine, utilisée en Europe au XIIIe s.",sk:"Navigation"},
{id:"hi1_20",lv:"histoire-cm1",cat:"Renaissance",diff:3,q:"Qui était Martin Luther ?",ch:["Un peintre","Un moine allemand qui critique l'Église catholique en 1517","Un roi","Un explorateur"],ans:1,se:"Martin Luther (1483-1546) affiche en 1517 ses 95 thèses critiquant l'Église : naissance du protestantisme.",pourquoi:"La Réforme protestante divise le christianisme en Europe.",regle:"Luther 1517 = Réforme protestante. Catholiques vs Protestants.",sk:"Réforme"}
);

EX.push(
/* ═══ HISTOIRE CM2 — Révolution / XIXe / XXe ═══ */
{id:"hi3_01",lv:"histoire-cm2",cat:"Révolution",diff:1,q:"En quelle année éclate la Révolution française ?",ch:["1492","1789","1914","2000"],ans:1,se:"La Révolution française commence en 1789. Le 14 juillet 1789, prise de la Bastille = fête nationale.",pourquoi:"1492 = découverte de l'Amérique. 1914 = début de la 1re Guerre mondiale.",regle:"1789 = Révolution française.",sk:"Dates clés"},
{id:"hi3_02",lv:"histoire-cm2",cat:"Révolution",diff:1,q:"Que se passe-t-il le 14 juillet 1789 ?",ch:["Naissance de Napoléon","Prise de la Bastille","Mort du roi","Signature de la paix"],ans:1,se:"Le 14 juillet 1789, le peuple parisien prend la Bastille (prison-symbole de l'absolutisme royal). C'est devenu la fête nationale française.",pourquoi:"Louis XVI sera exécuté en 1793.",regle:"14 juillet 1789 = prise de la Bastille = symbole de la Révolution.",sk:"Évènements clés"},
{id:"hi3_03",lv:"histoire-cm2",cat:"Révolution",diff:2,q:"Qui était roi de France en 1789 ?",ch:["Louis XIV","Louis XVI","Napoléon","Henri IV"],ans:1,se:"Louis XVI était roi en 1789. Il sera guillotiné le 21 janvier 1793.",pourquoi:"Louis XIV (le Roi Soleil) régnait au XVIIe siècle.",regle:"Louis XVI = roi pendant la Révolution. Marie-Antoinette était sa femme.",sk:"Rois de France"},
{id:"hi3_04",lv:"histoire-cm2",cat:"Révolution",diff:2,q:"Quels sont les 3 mots de la devise française ?",ch:["Bonté, Justice, Paix","Liberté, Égalité, Fraternité","Travail, Famille, Patrie","Honneur, Patrie, Roi"],ans:1,se:"'Liberté, Égalité, Fraternité' est la devise née de la Révolution française. Elle figure sur les bâtiments officiels.",pourquoi:"'Travail, Famille, Patrie' était la devise du régime de Vichy (1940-44), pas la devise républicaine.",regle:"Devise française = Liberté, Égalité, Fraternité (depuis la Révolution).",sk:"Symboles républicains"},
{id:"hi3_05",lv:"histoire-cm2",cat:"Révolution",diff:3,q:"La Déclaration des Droits de l'Homme et du Citoyen est de quelle année ?",ch:["1492","1789","1914","1958"],ans:1,se:"Adoptée le 26 août 1789, la DDHC affirme la liberté, l'égalité, la souveraineté du peuple.",pourquoi:"C'est un texte fondateur des droits humains modernes.",regle:"DDHC = 26 août 1789 (Révolution). Inspirée des Lumières.",sk:"Textes fondateurs"},
{id:"hi3_06",lv:"histoire-cm2",cat:"XIXe siècle",diff:2,q:"Qui devient empereur des Français en 1804 ?",ch:["Louis XVI","Napoléon Bonaparte","Charlemagne","Hugo"],ans:1,se:"Le 2 décembre 1804, Napoléon Bonaparte se sacre empereur dans Notre-Dame de Paris.",pourquoi:"Charlemagne, c'était en l'an 800 (Moyen Âge).",regle:"Napoléon Ier = empereur français de 1804 à 1815.",sk:"Empire"},
{id:"hi3_07",lv:"histoire-cm2",cat:"XIXe siècle",diff:3,q:"Quelle bataille a défait Napoléon en 1815 ?",ch:["Austerlitz","Waterloo","Marignan","Verdun"],ans:1,se:"Le 18 juin 1815, Napoléon est battu à Waterloo (Belgique) par les Anglais (Wellington) et les Prussiens.",pourquoi:"Austerlitz (1805) fut au contraire une grande victoire de Napoléon.",regle:"Waterloo = défaite finale de Napoléon (1815). Il est exilé à Sainte-Hélène.",sk:"Batailles"},
{id:"hi3_08",lv:"histoire-cm2",cat:"XIXe siècle",diff:2,q:"Au XIXe siècle, l'invention du chemin de fer (train) change la France. Qui en a bâti le premier réseau ?",ch:["Eiffel","Les frères Lumière","Stephenson (Anglais) puis Pereire et autres en France","Pasteur"],ans:2,se:"Le train s'impose au XIXe siècle. En France, le réseau s'étend rapidement à partir des années 1830.",pourquoi:"Eiffel a construit la tour, Pasteur le vaccin, les Lumière le cinéma.",regle:"Révolution industrielle au XIXe : train, machine à vapeur, usines.",sk:"Révolution industrielle"},
{id:"hi3_09",lv:"histoire-cm2",cat:"XIXe siècle",diff:1,q:"Qui a peint les Nymphéas (les nénuphars) ?",ch:["Picasso","Monet","Van Gogh","Renoir"],ans:1,se:"Claude Monet, peintre impressionniste, a peint la série des Nymphéas dans son jardin de Giverny.",pourquoi:"Tous sont des grands peintres mais sur d'autres sujets.",regle:"Monet = impressionniste, Nymphéas, jardin de Giverny.",sk:"Art moderne"},
{id:"hi3_10",lv:"histoire-cm2",cat:"XIXe siècle",diff:2,q:"Qui a inventé le vaccin contre la rage ?",ch:["Marie Curie","Louis Pasteur","Charles Darwin","Albert Einstein"],ans:1,se:"Louis Pasteur (1822-1895), chimiste et biologiste français, a inventé le vaccin contre la rage en 1885.",pourquoi:"Marie Curie : radioactivité. Darwin : évolution. Einstein : relativité.",regle:"Pasteur = pasteurisation et vaccin contre la rage.",sk:"Sciences XIXe"},
{id:"hi3_11",lv:"histoire-cm2",cat:"XXe siècle",diff:1,q:"En quelle année commence la Première Guerre mondiale ?",ch:["1789","1914","1939","2001"],ans:1,se:"La Première Guerre mondiale (la 'Grande Guerre') commence en 1914 et finit en 1918.",pourquoi:"1939 = Seconde Guerre mondiale.",regle:"Première Guerre mondiale : 1914-1918. Armistice = 11 novembre 1918.",sk:"Guerres mondiales"},
{id:"hi3_12",lv:"histoire-cm2",cat:"XXe siècle",diff:2,q:"Comment appelle-t-on les soldats français de 14-18 ?",ch:["Les chevaliers","Les poilus","Les mousquetaires","Les zouaves"],ans:1,se:"Les soldats français de 14-18 sont appelés les 'poilus' à cause de leurs barbes (rasoirs absents dans les tranchées).",pourquoi:"Les autres termes désignent d'autres époques.",regle:"Poilus = soldats français de la Première Guerre mondiale.",sk:"14-18"},
{id:"hi3_13",lv:"histoire-cm2",cat:"XXe siècle",diff:1,q:"En quelle année commence la Seconde Guerre mondiale ?",ch:["1914","1939","1969","2001"],ans:1,se:"La Seconde Guerre mondiale commence en 1939 (invasion de la Pologne par l'Allemagne nazie) et finit en 1945.",pourquoi:"1914 = Première Guerre mondiale.",regle:"Seconde Guerre mondiale : 1939-1945.",sk:"Guerres mondiales"},
{id:"hi3_14",lv:"histoire-cm2",cat:"XXe siècle",diff:2,q:"Qui dirigeait la France libre depuis Londres pendant la Seconde Guerre mondiale ?",ch:["Pétain","De Gaulle","Mitterrand","Chirac"],ans:1,se:"Le Général de Gaulle, depuis Londres, lance l'Appel du 18 juin 1940 et dirige la France libre. Pétain collaborait à Vichy.",pourquoi:"Pétain dirigeait au contraire le régime de Vichy, collaborant avec l'occupant nazi.",regle:"De Gaulle = chef de la France libre (1940-1944).",sk:"Seconde Guerre"},
{id:"hi3_15",lv:"histoire-cm2",cat:"XXe siècle",diff:3,q:"Quel évènement marque la fin de la Seconde Guerre mondiale en Europe ?",ch:["L'invasion de la Pologne","Le Débarquement (juin 1944)","La capitulation allemande (8 mai 1945)","Hiroshima"],ans:2,se:"Le 8 mai 1945, l'Allemagne nazie capitule. La guerre en Europe est finie.",pourquoi:"Le Débarquement (6 juin 1944) marque le début de la libération. Hiroshima (août 1945) finit la guerre dans le Pacifique.",regle:"8 mai 1945 = victoire en Europe. 2 sept 1945 = victoire totale (Japon).",sk:"Fin de la guerre"},
{id:"hi3_16",lv:"histoire-cm2",cat:"XXe siècle",diff:2,q:"Quand les femmes obtiennent-elles le droit de vote en France ?",ch:["1789","1914","1944","2000"],ans:2,se:"Les Françaises obtiennent le droit de vote par ordonnance du 21 avril 1944. Premier vote en 1945.",pourquoi:"Les Anglaises (1918), Américaines (1920) ou Allemandes (1918) l'avaient eu plus tôt.",regle:"Droit de vote des femmes en France = 1944.",sk:"Droits civiques"},
{id:"hi3_17",lv:"histoire-cm2",cat:"XXe siècle",diff:2,q:"En quelle année l'homme marche-t-il sur la Lune ?",ch:["1945","1969","1989","2010"],ans:1,se:"Le 21 juillet 1969, l'Américain Neil Armstrong est le premier homme à marcher sur la Lune (mission Apollo 11).",pourquoi:"'Un petit pas pour l'homme, un bond de géant pour l'humanité.'",regle:"1969 = premier pas sur la Lune (Armstrong, USA).",sk:"Conquête spatiale"},
{id:"hi3_18",lv:"histoire-cm2",cat:"XXe siècle",diff:3,q:"Quel mur, symbole de la Guerre froide, est tombé en 1989 ?",ch:["Le Mur de Chine","Le Mur de Berlin","Le Mur des Lamentations","Le Mur de la honte (Tijuana)"],ans:1,se:"Le 9 novembre 1989, le Mur de Berlin (séparant Berlin Est et Ouest depuis 1961) tombe. Symbole de la fin de la Guerre froide.",pourquoi:"Il séparait l'Allemagne communiste (Est) et démocratique (Ouest).",regle:"1989 = chute du Mur de Berlin. 1991 = fin de l'URSS.",sk:"Guerre froide"},
{id:"hi3_19",lv:"histoire-cm2",cat:"XXe siècle",diff:1,q:"Quand l'euro (€) remplace-t-il le franc en France ?",ch:["1989","2002","2010","2020"],ans:1,se:"L'euro est mis en circulation le 1er janvier 2002. Le franc disparaît.",pourquoi:"L'euro existe depuis 1999 mais en monnaie scripturale (banques) seulement.",regle:"2002 = passage à l'euro en France (et 11 autres pays).",sk:"Construction européenne"},
{id:"hi3_20",lv:"histoire-cm2",cat:"Révolution",diff:3,q:"Quel symbole républicain représente la République française ?",ch:["Marianne","Vercingétorix","Charlemagne","Napoléon"],ans:0,se:"Marianne, femme coiffée d'un bonnet phrygien, symbolise la République française depuis la Révolution.",pourquoi:"On la voit sur les pièces, les timbres, les mairies.",regle:"Marianne = symbole de la République (depuis 1789).",sk:"Symboles républicains"}
);
